#pragma once

#include "wpn_shared/wpn_usp.h"
#include "wpn_shared/wpn_ak47.h"
#include "wpn_shared/wpn_aug.h"
#include "wpn_shared/wpn_awp.h"
#include "wpn_shared/wpn_c4.h"
#include "wpn_shared/wpn_deagle.h"
#include "wpn_shared/wpn_flashbang.h"
#include "wpn_shared/wpn_glock18.h"
#include "wpn_shared/wpn_hegrenade.h"
#include "wpn_shared/wpn_knife.h"
#include "wpn_shared/wpn_m3.h"
#include "wpn_shared/wpn_m4a1.h"
#include "wpn_shared/wpn_p90.h"
#include "wpn_shared/wpn_scout.h"
#include "wpn_shared/wpn_smokegrenade.h"
#include "wpn_shared/wpn_sg550.h"