
#include "extdll.h"
#include "util.h"
#include "game.h"
#include "globals.h"

/*
* Globals initialization
*/
cvar_t *g_psv_gravity = NULL;
cvar_t *g_psv_aim = NULL;
cvar_t *g_footsteps = NULL;
cvar_t *g_psv_accelerate = NULL;
cvar_t *g_psv_friction = NULL;
cvar_t *g_psv_stopspeed = NULL;
cvar_t displaysoundlist = { "displaysoundlist", "0", 0, 0.0f, NULL };
cvar_t timelimit = { "mp_timelimit", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t flashlight = { "mp_flashlight", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t decalfrequency = { "decalfrequency", "30", FCVAR_SERVER, 0.0f, NULL };
cvar_t fadetoblack = { "mp_fadetoblack", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t fragsleft = { "mp_fragsleft", "0", FCVAR_SERVER | FCVAR_UNLOGGED, 0.0f, NULL };
cvar_t timeleft = { "mp_timeleft", "0", FCVAR_SERVER | FCVAR_UNLOGGED, 0.0f, NULL };
cvar_t friendlyfire = { "mp_friendlyfire", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t allowmonsters = { "mp_allowmonsters", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t roundtime = { "mp_roundtime", "3", FCVAR_SERVER, 0.0f, NULL };
cvar_t buytime = { "mp_buytime", "1.5", FCVAR_SERVER, 0.0f, NULL };
cvar_t freezetime = { "mp_freezetime", "3", FCVAR_SERVER, 0.0f, NULL };
cvar_t c4timer = { "mp_c4timer", "45", FCVAR_SERVER, 0.0f, NULL };
cvar_t ghostfrequency = { "mp_ghostfrequency", "0.1", FCVAR_SERVER, 0.0f, NULL };
cvar_t autokick = { "mp_autokick", "1", FCVAR_SERVER, 0.0f, NULL };
cvar_t autokick_timeout = { "mp_autokick_timeout", "-1", FCVAR_SERVER, 0.0f, NULL };
cvar_t restartround = { "sv_restartround", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t sv_restart = { "sv_restart", "0", FCVAR_SERVER, 0.0f, NULL };



cvar_t pbhithuman = { "sv_hithuman_sound", "0", FCVAR_SERVER, 0.0f, NULL };


cvar_t cl_delaykill = { "cl_delaykill", "0.2", FCVAR_SERVER, 0.0f, NULL };


cvar_t tracer = { "sv_tracer_effect", "0", FCVAR_SERVER, 0.0f, NULL };

cvar_t annhs = { "annhs", "0", 0, 0.0f, NULL };


cvar_t limitteams = { "mp_limitteams", "2", FCVAR_SERVER, 0.0f, NULL };
cvar_t autoteambalance = { "mp_autoteambalance", "1", FCVAR_SERVER, 0.0f, NULL };
cvar_t tkpunish = { "mp_tkpunish", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t hostagepenalty = { "mp_hostagepenalty", "13", FCVAR_SERVER, 0.0f, NULL };
cvar_t mirrordamage = { "mp_mirrordamage", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t logmessages = { "mp_logmessages", "1", FCVAR_SERVER, 0.0f, NULL };
cvar_t forcecamera = { "mp_forcecamera", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t forcechasecam = { "mp_forcechasecam", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t mapvoteratio = { "mp_mapvoteratio", "0.66", FCVAR_SERVER, 0.0f, NULL };
cvar_t logdetail = { "mp_logdetail", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t startmoney = { "mp_startmoney", "800", FCVAR_SERVER, 0.0f, NULL };
cvar_t maxrounds = { "mp_maxrounds", "13", FCVAR_SERVER, 0.0f, NULL };
cvar_t winlimit = { "mp_winlimit", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t windifference = { "mp_windifference", "1", FCVAR_SERVER, 0.0f, NULL };
cvar_t playerid = { "mp_playerid", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t allow_spectators = { "allow_spectators", "1.0", FCVAR_SERVER, 0.0f, NULL };
cvar_t mp_chattime = { "mp_chattime", "10", FCVAR_SERVER, 0.0f, NULL };
cvar_t kick_percent = { "mp_kickpercent", "0.66", FCVAR_SERVER, 0.0f, NULL };
cvar_t humans_join_team = { "humans_join_team", "any", FCVAR_SERVER, 0.0f, NULL };
cvar_t sk_plr_9mm_bullet1 = { "sk_plr_9mm_bullet1", "0", 0, 0.0f, NULL };
cvar_t sk_plr_9mm_bullet2 = { "sk_plr_9mm_bullet2", "0", 0, 0.0f, NULL };
cvar_t sk_plr_9mm_bullet3 = { "sk_plr_9mm_bullet3", "0", 0, 0.0f, NULL };
cvar_t sk_plr_357_bullet1 = { "sk_plr_357_bullet1", "0", 0, 0.0f, NULL };
cvar_t sk_plr_357_bullet2 = { "sk_plr_357_bullet2", "0", 0, 0.0f, NULL };
cvar_t sk_plr_357_bullet3 = { "sk_plr_357_bullet3", "0", 0, 0.0f, NULL };
cvar_t sk_plr_9mmAR_bullet1 = { "sk_plr_9mmAR_bullet1", "0", 0, 0.0f, NULL };
cvar_t sk_plr_9mmAR_bullet2 = { "sk_plr_9mmAR_bullet2", "0", 0, 0.0f, NULL };
cvar_t sk_plr_9mmAR_bullet3 = { "sk_plr_9mmAR_bullet3", "0", 0, 0.0f, NULL };
cvar_t sk_plr_9mmAR_grenade1 = { "sk_plr_9mmAR_grenade1", "0", 0, 0.0f, NULL };
cvar_t sk_plr_9mmAR_grenade2 = { "sk_plr_9mmAR_grenade2", "0", 0, 0.0f, NULL };
cvar_t sk_plr_9mmAR_grenade3 = { "sk_plr_9mmAR_grenade3", "0", 0, 0.0f, NULL };
cvar_t sk_plr_buckshot1 = { "sk_plr_buckshot1", "0", 0, 0.0f, NULL };
cvar_t sk_plr_buckshot2 = { "sk_plr_buckshot2", "0", 0, 0.0f, NULL };
cvar_t sk_plr_buckshot3 = { "sk_plr_buckshot3", "0", 0, 0.0f, NULL };
cvar_t sk_plr_rpg1 = { "sk_plr_rpg1", "0", 0, 0.0f, NULL };
cvar_t sk_plr_rpg2 = { "sk_plr_rpg2", "0", 0, 0.0f, NULL };
cvar_t sk_plr_rpg3 = { "sk_plr_rpg3", "0", 0, 0.0f, NULL };
cvar_t sk_12mm_bullet1 = { "sk_12mm_bullet1", "0", 0, 0.0f, NULL };
cvar_t sk_12mm_bullet2 = { "sk_12mm_bullet2", "0", 0, 0.0f, NULL };
cvar_t sk_12mm_bullet3 = { "sk_12mm_bullet3", "0", 0, 0.0f, NULL };
cvar_t sk_9mmAR_bullet1 = { "sk_9mmAR_bullet1", "0", 0, 0.0f, NULL };
cvar_t sk_9mmAR_bullet2 = { "sk_9mmAR_bullet2", "0", 0, 0.0f, NULL };
cvar_t sk_9mmAR_bullet3 = { "sk_9mmAR_bullet3", "0", 0, 0.0f, NULL };
cvar_t sk_9mm_bullet1 = { "sk_9mm_bullet1", "0", 0, 0.0f, NULL };
cvar_t sk_9mm_bullet2 = { "sk_9mm_bullet2", "0", 0, 0.0f, NULL };
cvar_t sk_9mm_bullet3 = { "sk_9mm_bullet3", "0", 0, 0.0f, NULL };
cvar_t sk_suitcharger1 = { "sk_suitcharger1", "0", 0, 0.0f, NULL };
cvar_t sk_suitcharger2 = { "sk_suitcharger2", "0", 0, 0.0f, NULL };
cvar_t sk_suitcharger3 = { "sk_suitcharger3", "0", 0, 0.0f, NULL };
cvar_t sk_battery1 = { "sk_battery1", "0", 0, 0.0f, NULL };
cvar_t sk_battery2 = { "sk_battery2", "0", 0, 0.0f, NULL };
cvar_t sk_battery3 = { "sk_battery3", "0", 0, 0.0f, NULL };
cvar_t sk_healthcharger1 = { "sk_healthcharger1", "0", 0, 0.0f, NULL };
cvar_t sk_healthcharger2 = { "sk_healthcharger2", "0", 0, 0.0f, NULL };
cvar_t sk_healthcharger3 = { "sk_healthcharger3", "0", 0, 0.0f, NULL };
cvar_t sk_healthkit1 = { "sk_healthkit1", "0", 0, 0.0f, NULL };
cvar_t sk_healthkit2 = { "sk_healthkit2", "0", 0, 0.0f, NULL };
cvar_t sk_healthkit3 = { "sk_healthkit3", "0", 0, 0.0f, NULL };
cvar_t sk_scientist_heal1 = { "sk_scientist_heal1", "0", 0, 0.0f, NULL };
cvar_t sk_scientist_heal2 = { "sk_scientist_heal2", "0", 0, 0.0f, NULL };
cvar_t sk_scientist_heal3 = { "sk_scientist_heal3", "0", 0, 0.0f, NULL };

cvar_t gamemode = { "mp_gamemode", "none", FCVAR_SERVER, 0.0f, NULL };
cvar_t maxkills = { "mp_maxkills", "150", FCVAR_SERVER, 0.0f, NULL };


cvar_t weapon_damage_game_ak47 = { "weapon_damage_ak47", "20",NULL, 0.0f, NULL };
cvar_t weapon_damage_game_aksopmod = { "weapon_damage_aksopmod", "20",NULL, 0.0f, NULL };
cvar_t weapon_damage_game_aug_hbar = { "weapon_damage_aug_hbar", "20",NULL, 0.0f, NULL };
cvar_t weapon_damage_game_aug = { "weapon_damage_aug", "20",NULL, 0.0f, NULL };
cvar_t weapon_damage_game_augblitz = { "weapon_damage_augblitz", "20",NULL, 0.0f, NULL };
cvar_t weapon_damage_game_p90 = { "weapon_damage_p90", "20",NULL, 0.0f, NULL };
cvar_t weapon_damage_game_aug_a3_silencer = { "weapon_damage_aug_silencer", "20",NULL, 0.0f, NULL };
cvar_t weapon_damage_game_f2000 = { "weapon_damage_f2000", "20",NULL, 0.0f, NULL };
cvar_t weapon_damage_game_famas_g2 = { "weapon_damage_famas_g2", "20",NULL, 0.0f, NULL };
cvar_t weapon_damage_game_g36c = { "weapon_damage_g36c", "20",NULL, 0.0f, NULL };
cvar_t weapon_damage_game_k1 = { "weapon_damage_k1", "20",NULL, 0.0f, NULL };
cvar_t weapon_damage_game_k2 = { "weapon_damage_k2", "20",NULL, 0.0f, NULL };
cvar_t weapon_damage_game_kriss_sv = { "weapon_damage_kriss_sv", "20",NULL, 0.0f, NULL };
cvar_t weapon_damage_game_kriss_sv_dual = { "weapon_damage_kriss_sv_dual", "20",NULL, 0.0f, NULL };
cvar_t weapon_damage_game_kriss_sv_silencer = { "weapon_damage_kriss_sv_silencer", "20",NULL, 0.0f, NULL };
cvar_t weapon_damage_game_kriss_sv_silencer_dual = { "weapon_damage_kriss_sv_silencer_dual", "20",NULL, 0.0f, NULL };
cvar_t weapon_damage_game_m4_cqb_lv1 = { "weapon_damage_m4_cqb_lv1", "20",NULL, 0.0f, NULL };
cvar_t weapon_damage_game_m4_cqb_lv2 = { "weapon_damage_m4_cqb_lv2", "20",NULL, 0.0f, NULL };
cvar_t weapon_damage_game_m4a1 = { "weapon_damage_m4a1", "20",NULL, 0.0f, NULL };
cvar_t weapon_damage_game_m4a1_s = { "weapon_damage_m4a1_s", "20",NULL, 0.0f, NULL };
cvar_t weapon_damage_game_mp7 = { "weapon_damage_mp7", "20",NULL, 0.0f, NULL };
cvar_t weapon_damage_game_oa93 = { "weapon_damage_oa93", "20",NULL, 0.0f, NULL };
cvar_t weapon_damage_game_oa93_dual = { "weapon_damage_oa93_dual", "20",NULL, 0.0f, NULL };
cvar_t weapon_damage_game_p90_mc = { "weapon_damage_p90_mc", "20",NULL, 0.0f, NULL };
cvar_t weapon_damage_game_pindad_ss2_v5 = { "weapon_damage_pindad_ss2_v5", "20",NULL, 0.0f, NULL };
cvar_t weapon_damage_game_groza = { "weapon_damage_groza", "20",NULL, 0.0f, NULL };
cvar_t weapon_damage_game_sc2010 = { "weapon_damage_sc2010", "20",NULL, 0.0f, NULL };
cvar_t weapon_damage_game_scar_carbine = { "weapon_damage_scar_carbine", "20",NULL, 0.0f, NULL };
cvar_t weapon_damage_game_kriss_sv_crb = { "weapon_damage_kriss_sv_crb", "20",NULL, 0.0f, NULL };
cvar_t weapon_damage_game_kriss_sv_crb_dual = { "weapon_damage_kriss_sv_crb_dual", "20",NULL, 0.0f, NULL };
cvar_t weapon_damage_game_mp5k = { "weapon_damage_mp5k", "20",NULL, 0.0f, NULL };
cvar_t weapon_damage_game_m4_azure = { "weapon_damage_m4_azure", "20",NULL, 0.0f, NULL };
cvar_t weapon_damage_game_mp9 = { "weapon_damage_mp9", "20",NULL, 0.0f, NULL };
cvar_t weapon_damage_game_sg550 = { "weapon_damage_sg550", "20",NULL, 0.0f, NULL };
cvar_t weapon_damage_game_l115a1 = { "weapon_damage_l115a1", "20",NULL, 0.0f, NULL };
cvar_t weapon_damage_game_cheytac_m200 = { "weapon_damage_cheytac_m200", "20",NULL, 0.0f, NULL };
cvar_t weapon_damage_game_dragunov = { "weapon_damage_dragunov", "20",NULL, 0.0f, NULL };
cvar_t weapon_damage_game_kar98k = { "weapon_damage_kar98k", "20",NULL, 0.0f, NULL };
cvar_t weapon_damage_game_rangemaster_338 = { "weapon_damage_rangemaster_338", "20",NULL, 0.0f, NULL };
cvar_t weapon_damage_game_m82a1 = { "weapon_damage_m82a1", "20",NULL, 0.0f, NULL };
cvar_t weapon_damage_game_tactilite_t2 = { "weapon_damage_tactilite_t2", "20",NULL, 0.0f, NULL };
cvar_t weapon_damage_game_ssg69 = { "weapon_damage_ssg69", "20",NULL, 0.0f, NULL };
cvar_t weapon_damage_game_m4_spr_lv1 = { "weapon_damage_m4_spr_lv1", "20",NULL, 0.0f, NULL };
cvar_t weapon_damage_game_m4_spr_lv2 = { "weapon_damage_m4_spr_lv2", "20",NULL, 0.0f, NULL };
cvar_t weapon_damage_game_m1887 = { "weapon_damage_m1887", "20",NULL, 0.0f, NULL };
cvar_t weapon_damage_game_spas_15 = { "weapon_damage_spas_15", "20",NULL, 0.0f, NULL };
cvar_t weapon_damage_game_zombie_s = { "weapon_damage_zombie_s", "20",NULL, 0.0f, NULL };
cvar_t weapon_damage_game_870mcs = { "weapon_damage_870mcs", "20",NULL, 0.0f, NULL };
cvar_t weapon_damage_game_ak_sopmod_cg = { "weapon_damage_ak_sopmpd_cg", "20",NULL, 0.0f, NULL };
cvar_t weapon_damage_game_aug_esport = { "weapon_damage_aug_esport", "20",NULL, 0.0f, NULL };
cvar_t weapon_damage_game_t77 = { "weapon_damage_t77", "20",NULL, 0.0f, NULL };
cvar_t weapon_damage_game_t77_dual = { "weapon_damage_t77_dual", "20",NULL, 0.0f, NULL };
cvar_t weapon_damage_game_apc = { "weapon_damage_apc", "20",NULL, 0.0f, NULL };
cvar_t weapon_damage_game_fg42 = { "weapon_damage_fg42", "20",NULL, 0.0f, NULL };
cvar_t weapon_damage_game_msbs = { "weapon_damage_msbs", "20",NULL, 0.0f, NULL };
cvar_t weapon_damage_game_as50 = { "weapon_damage_as50", "20",NULL, 0.0f, NULL };
cvar_t weapon_damage_game_m1887_w = { "weapon_damage_m1887_w", "20",NULL, 0.0f, NULL };
cvar_t weapon_damage_game_pgm = { "weapon_damage_pgm", "20",NULL, 0.0f, NULL };
cvar_t weapon_damage_game_ump = { "weapon_damage_ump", "20",NULL, 0.0f, NULL };
cvar_t weapon_damage_game_sig = { "weapon_damage_sig", "20",NULL, 0.0f, NULL };
cvar_t weapon_damage_game_spectre = { "weapon_damage_spectre", "20",NULL, 0.0f, NULL };
cvar_t weapon_damage_game_tar = { "weapon_damage_tar21", "20",NULL, 0.0f, NULL };
cvar_t weapon_damage_game_xm8 = { "weapon_damage_xm8", "20",NULL, 0.0f, NULL };
cvar_t weapon_damage_game_water_gun = { "weapon_damage_watergun", "20",NULL, 0.0f, NULL };//
cvar_t weapon_damage_game_colt_python = { "weapon_damage_colt_python", "20",NULL, 0.0f, NULL };
cvar_t weapon_damage_game_deagle_dual = { "weapon_damage_deagle_dual", "20",NULL, 0.0f, NULL };
cvar_t weapon_damage_game_dual_handgun = { "weapon_damage_dual_handgun", "20",NULL, 0.0f, NULL };
cvar_t weapon_damage_game_raging_bull = { "weapon_damage_raging_bull", "20",NULL, 0.0f, NULL };
cvar_t weapon_damage_game_deagle = { "weapon_damage_deagle", "20",NULL, 0.0f, NULL };
cvar_t weapon_damage_game_k5 = { "weapon_damage_k5", "20",NULL, 0.0f, NULL };
cvar_t weapon_damage_game_glock = { "weapon_damage_glock", "20",NULL, 0.0f, NULL };

//draw
cvar_t weapon_draw_time_ak47 = { "weapon_draw_time_ak47", "0.5", 0, 0.0f, NULL };
cvar_t weapon_draw_time_aksopmod = { "weapon_draw_time_aksopmod", "0.5", 0, 0.0f, NULL };
cvar_t weapon_draw_time_aug_hbar = { "weapon_draw_time_aug_hbar", "0.5", 0, 0.0f, NULL };
cvar_t weapon_draw_time_aug = { "weapon_draw_time_aug", "0.5", 0, 0.0f, NULL };
cvar_t weapon_draw_time_augblitz = { "weapon_draw_time_augblitz", "0.5", 0, 0.0f, NULL };
cvar_t weapon_draw_time_p90 = { "weapon_draw_time_p90", "0.5", 0, 0.0f, NULL };
cvar_t weapon_draw_time_aug_a3_silencer = { "weapon_draw_time_aug_silencer", "0.5", 0, 0.0f, NULL };
cvar_t weapon_draw_time_f2000 = { "weapon_draw_time_f2000", "0.5", 0, 0.0f, NULL };
cvar_t weapon_draw_time_famas_g2 = { "weapon_draw_time_famas_g2", "0.5", 0, 0.0f, NULL };
cvar_t weapon_draw_time_g36c = { "weapon_draw_time_g36c", "0.5", 0, 0.0f, NULL };
cvar_t weapon_draw_time_k1 = { "weapon_draw_time_k1", "0.5", 0, 0.0f, NULL };
cvar_t weapon_draw_time_k2 = { "weapon_draw_time_k2", "0.5", 0, 0.0f, NULL };
cvar_t weapon_draw_time_kriss_sv = { "weapon_draw_time_kriss_sv", "0.5", 0, 0.0f, NULL };
cvar_t weapon_draw_time_kriss_sv_dual = { "weapon_draw_time_kriss_sv_dual", "0.5", 0, 0.0f, NULL };
cvar_t weapon_draw_time_kriss_sv_silencer = { "weapon_draw_time_kriss_sv_silencer", "0.5", 0, 0.0f, NULL };
cvar_t weapon_draw_time_kriss_sv_silencer_dual = { "weapon_draw_time_kriss_sv_silencer_dual", "0.5", 0, 0.0f, NULL };
cvar_t weapon_draw_time_m4_cqb_lv1 = { "weapon_draw_time_m4_cqb_lv1", "0.5", 0, 0.0f, NULL };
cvar_t weapon_draw_time_m4_cqb_lv2 = { "weapon_draw_time_m4_cqb_lv2", "0.5", 0, 0.0f, NULL };
cvar_t weapon_draw_time_m4a1 = { "weapon_draw_time_m4a1", "0.5", 0, 0.0f, NULL };
cvar_t weapon_draw_time_m4a1_s = { "weapon_draw_time_m4a1_s", "0.5", 0, 0.0f, NULL };
cvar_t weapon_draw_time_mp7 = { "weapon_draw_time_mp7", "0.5", 0, 0.0f, NULL };
cvar_t weapon_draw_time_oa93 = { "weapon_draw_time_oa93", "0.5", 0, 0.0f, NULL };
cvar_t weapon_draw_time_oa93_dual = { "weapon_draw_time_oa93_dual", "0.5", 0, 0.0f, NULL };
cvar_t weapon_draw_time_p90_mc = { "weapon_draw_time_p90_mc", "0.5", 0, 0.0f, NULL };
cvar_t weapon_draw_time_pindad_ss2_v5 = { "weapon_draw_time_pindad_ss2_v5", "0.5", 0, 0.0f, NULL };
cvar_t weapon_draw_time_groza = { "weapon_draw_time_groza", "0.5", 0, 0.0f, NULL };
cvar_t weapon_draw_time_sc2010 = { "weapon_draw_time_sc2010", "0.5", 0, 0.0f, NULL };
cvar_t weapon_draw_time_scar_carbine = { "weapon_draw_time_scar_carbine", "0.5", 0, 0.0f, NULL };
cvar_t weapon_draw_time_kriss_sv_crb = { "weapon_draw_time_kriss_sv_crb", "0.5", 0, 0.0f, NULL };
cvar_t weapon_draw_time_kriss_sv_crb_dual = { "weapon_draw_time_kriss_sv_crb_dual", "0.5", 0, 0.0f, NULL };
cvar_t weapon_draw_time_mp5k = { "weapon_draw_time_mp5k", "0.5", 0, 0.0f, NULL };
cvar_t weapon_draw_time_m4_azure = { "weapon_draw_time_m4_azure", "0.5", 0, 0.0f, NULL };
cvar_t weapon_draw_time_mp9 = { "weapon_draw_time_mp9", "0.5", 0, 0.0f, NULL };
cvar_t weapon_draw_time_sg550 = { "weapon_draw_time_sg550", "0.5", 0, 0.0f, NULL };
cvar_t weapon_draw_time_l115a1 = { "weapon_draw_time_l115a1", "0.5", 0, 0.0f, NULL };
cvar_t weapon_draw_time_cheytac_m200 = { "weapon_draw_time_cheytac_m200", "0.5", 0, 0.0f, NULL };
cvar_t weapon_draw_time_dragunov = { "weapon_draw_time_dragunov", "0.5", 0, 0.0f, NULL };
cvar_t weapon_draw_time_kar98k = { "weapon_draw_time_kar98k", "0.5", 0, 0.0f, NULL };
cvar_t weapon_draw_time_rangemaster_338 = { "weapon_draw_time_rangemaster_338", "0.5", 0, 0.0f, NULL };
cvar_t weapon_draw_time_m82a1 = { "weapon_draw_time_m82a1", "0.5", 0, 0.0f, NULL };
cvar_t weapon_draw_time_tactilite_t2 = { "weapon_draw_time_tactilite_t2", "0.5", 0, 0.0f, NULL };
cvar_t weapon_draw_time_ssg69 = { "weapon_draw_time_ssg69", "0.5", 0, 0.0f, NULL };
cvar_t weapon_draw_time_m4_spr_lv1 = { "weapon_draw_time_m4_spr_lv1", "0.5", 0, 0.0f, NULL };
cvar_t weapon_draw_time_m4_spr_lv2 = { "weapon_draw_time_m4_spr_lv2", "0.5", 0, 0.0f, NULL };
cvar_t weapon_draw_time_m1887 = { "weapon_draw_time_m1887", "0.5", 0, 0.0f, NULL };
cvar_t weapon_draw_time_spas_15 = { "weapon_draw_time_spas_15", "0.5", 0, 0.0f, NULL };
cvar_t weapon_draw_time_zombie_s = { "weapon_draw_time_zombie_s", "0.5", 0, 0.0f, NULL };
cvar_t weapon_draw_time_870mcs = { "weapon_draw_time_870mcs", "0.5", 0, 0.0f, NULL };
cvar_t weapon_draw_time_ak_sopmod_cg = { "weapon_draw_time_ak_sopmpd_cg", "0.5", 0, 0.0f, NULL };
cvar_t weapon_draw_time_aug_esport = { "weapon_draw_time_aug_esport", "0.5", 0, 0.0f, NULL };
cvar_t weapon_draw_time_t77 = { "weapon_draw_time_t77", "0.5", 0, 0.0f, NULL };
cvar_t weapon_draw_time_t77_dual = { "weapon_draw_time_t77_dual", "0.5", 0, 0.0f, NULL };
cvar_t weapon_draw_time_apc = { "weapon_draw_time_apc", "0.5", 0, 0.0f, NULL };
cvar_t weapon_draw_time_fg42 = { "weapon_draw_time_fg42", "0.5", 0, 0.0f, NULL };
cvar_t weapon_draw_time_msbs = { "weapon_draw_time_msbs", "0.5", 0, 0.0f, NULL };
cvar_t weapon_draw_time_as50 = { "weapon_draw_time_as50", "0.5", 0, 0.0f, NULL };
cvar_t weapon_draw_time_m1887_w = { "weapon_draw_time_m1887_w", "0.5", 0, 0.0f, NULL };
cvar_t weapon_draw_time_pgm = { "weapon_draw_time_pgm", "0.5", 0, 0.0f, NULL };
cvar_t weapon_draw_time_ump = { "weapon_draw_time_ump", "0.5", 0, 0.0f, NULL };
cvar_t weapon_draw_time_sig = { "weapon_draw_time_sig", "0.5", 0, 0.0f, NULL };
cvar_t weapon_draw_time_spectre = { "weapon_draw_time_spectre", "0.5", 0, 0.0f, NULL };
cvar_t weapon_draw_time_tar = { "weapon_draw_time_tar21", "0.5", 0, 0.0f, NULL };
cvar_t weapon_draw_time_xm8 = { "weapon_draw_time_xm8", "0.5", 0, 0.0f, NULL };
cvar_t weapon_draw_time_water_gun = { "weapon_draw_time_watergun", "0.5", 0, 0.0f, NULL };//
cvar_t weapon_draw_time_colt_python = { "weapon_draw_time_colt_python", "0.5", 0, 0.0f, NULL };
cvar_t weapon_draw_time_deagle_dual = { "weapon_draw_time_deagle_dual", "0.5", 0, 0.0f, NULL };
cvar_t weapon_draw_time_dual_handgun = { "weapon_draw_time_dual_handgun", "0.5", 0, 0.0f, NULL };
cvar_t weapon_draw_time_raging_bull = { "weapon_draw_time_raging_bull", "0.5", 0, 0.0f, NULL };
cvar_t weapon_draw_time_deagle = { "weapon_draw_time_deagle", "0.5", 0, 0.0f, NULL };
cvar_t weapon_draw_time_k5 = { "weapon_draw_time_k5", "0.5", 0, 0.0f, NULL };
cvar_t weapon_draw_time_glock = { "weapon_draw_time_glock", "0.5", 0, 0.0f, NULL };

//reload
cvar_t weapon_reload_time_ak47 = { "weapon_reload_time_ak47", "0.5", 0, 0.0f, NULL };
cvar_t weapon_reload_time_aksopmod = { "weapon_reload_time_aksopmod", "0.5", 0, 0.0f, NULL };
cvar_t weapon_reload_time_aug_hbar = { "weapon_reload_time_aug_hbar", "0.5", 0, 0.0f, NULL };
cvar_t weapon_reload_time_aug = { "weapon_reload_time_aug", "0.5", 0, 0.0f, NULL };
cvar_t weapon_reload_time_augblitz = { "weapon_reload_time_augblitz", "0.5", 0, 0.0f, NULL };
cvar_t weapon_reload_time_p90 = { "weapon_reload_time_p90", "0.5", 0, 0.0f, NULL };
cvar_t weapon_reload_time_aug_a3_silencer = { "weapon_reload_time_aug_silencer", "0.5", 0, 0.0f, NULL };
cvar_t weapon_reload_time_f2000 = { "weapon_reload_time_f2000", "0.5", 0, 0.0f, NULL };
cvar_t weapon_reload_time_famas_g2 = { "weapon_reload_time_famas_g2", "0.5", 0, 0.0f, NULL };
cvar_t weapon_reload_time_g36c = { "weapon_reload_time_g36c", "0.5", 0, 0.0f, NULL };
cvar_t weapon_reload_time_k1 = { "weapon_reload_time_k1", "0.5", 0, 0.0f, NULL };
cvar_t weapon_reload_time_k2 = { "weapon_reload_time_k2", "0.5", 0, 0.0f, NULL };
cvar_t weapon_reload_time_kriss_sv = { "weapon_reload_time_kriss_sv", "0.5", 0, 0.0f, NULL };
cvar_t weapon_reload_time_kriss_sv_dual = { "weapon_reload_time_kriss_sv_dual", "0.5", 0, 0.0f, NULL };
cvar_t weapon_reload_time_kriss_sv_silencer = { "weapon_reload_time_kriss_sv_silencer", "0.5", 0, 0.0f, NULL };
cvar_t weapon_reload_time_kriss_sv_silencer_dual = { "weapon_reload_time_kriss_sv_silencer_dual", "0.5", 0, 0.0f, NULL };
cvar_t weapon_reload_time_m4_cqb_lv1 = { "weapon_reload_time_m4_cqb_lv1", "0.5", 0, 0.0f, NULL };
cvar_t weapon_reload_time_m4_cqb_lv2 = { "weapon_reload_time_m4_cqb_lv2", "0.5", 0, 0.0f, NULL };
cvar_t weapon_reload_time_m4a1 = { "weapon_reload_time_m4a1", "0.5", 0, 0.0f, NULL };
cvar_t weapon_reload_time_m4a1_s = { "weapon_reload_time_m4a1_s", "0.5", 0, 0.0f, NULL };
cvar_t weapon_reload_time_mp7 = { "weapon_reload_time_mp7", "0.5", 0, 0.0f, NULL };
cvar_t weapon_reload_time_oa93 = { "weapon_reload_time_oa93", "0.5", 0, 0.0f, NULL };
cvar_t weapon_reload_time_oa93_dual = { "weapon_reload_time_oa93_dual", "0.5", 0, 0.0f, NULL };
cvar_t weapon_reload_time_p90_mc = { "weapon_reload_time_p90_mc", "0.5", 0, 0.0f, NULL };
cvar_t weapon_reload_time_pindad_ss2_v5 = { "weapon_reload_time_pindad_ss2_v5", "0.5", 0, 0.0f, NULL };
cvar_t weapon_reload_time_groza = { "weapon_reload_time_groza", "0.5", 0, 0.0f, NULL };
cvar_t weapon_reload_time_sc2010 = { "weapon_reload_time_sc2010", "0.5", 0, 0.0f, NULL };
cvar_t weapon_reload_time_scar_carbine = { "weapon_reload_time_scar_carbine", "0.5", 0, 0.0f, NULL };
cvar_t weapon_reload_time_kriss_sv_crb = { "weapon_reload_time_kriss_sv_crb", "0.5", 0, 0.0f, NULL };
cvar_t weapon_reload_time_kriss_sv_crb_dual = { "weapon_reload_time_kriss_sv_crb_dual", "0.5", 0, 0.0f, NULL };
cvar_t weapon_reload_time_mp5k = { "weapon_reload_time_mp5k", "0.5", 0, 0.0f, NULL };
cvar_t weapon_reload_time_m4_azure = { "weapon_reload_time_m4_azure", "0.5", 0, 0.0f, NULL };
cvar_t weapon_reload_time_mp9 = { "weapon_reload_time_mp9", "0.5", 0, 0.0f, NULL };
cvar_t weapon_reload_time_sg550 = { "weapon_reload_time_sg550", "0.5", 0, 0.0f, NULL };
cvar_t weapon_reload_time_l115a1 = { "weapon_reload_time_l115a1", "0.5", 0, 0.0f, NULL };
cvar_t weapon_reload_time_cheytac_m200 = { "weapon_reload_time_cheytac_m200", "0.5", 0, 0.0f, NULL };
cvar_t weapon_reload_time_dragunov = { "weapon_reload_time_dragunov", "0.5", 0, 0.0f, NULL };
cvar_t weapon_reload_time_kar98k = { "weapon_reload_time_kar98k", "0.5", 0, 0.0f, NULL };
cvar_t weapon_reload_time_rangemaster_338 = { "weapon_reload_time_rangemaster_338", "0.5", 0, 0.0f, NULL };
cvar_t weapon_reload_time_m82a1 = { "weapon_reload_time_m82a1", "0.5", 0, 0.0f, NULL };
cvar_t weapon_reload_time_tactilite_t2 = { "weapon_reload_time_tactilite_t2", "0.5", 0, 0.0f, NULL };
cvar_t weapon_reload_time_ssg69 = { "weapon_reload_time_ssg69", "0.5", 0, 0.0f, NULL };
cvar_t weapon_reload_time_m4_spr_lv1 = { "weapon_reload_time_m4_spr_lv1", "0.5", 0, 0.0f, NULL };
cvar_t weapon_reload_time_m4_spr_lv2 = { "weapon_reload_time_m4_spr_lv2", "0.5", 0, 0.0f, NULL };
cvar_t weapon_reload_time_m1887 = { "weapon_reload_time_m1887", "0.5", 0, 0.0f, NULL };
cvar_t weapon_reload_time_spas_15 = { "weapon_reload_time_spas_15", "0.5", 0, 0.0f, NULL };
cvar_t weapon_reload_time_zombie_s = { "weapon_reload_time_zombie_s", "0.5", 0, 0.0f, NULL };
cvar_t weapon_reload_time_870mcs = { "weapon_reload_time_870mcs", "0.5", 0, 0.0f, NULL };
cvar_t weapon_reload_time_ak_sopmod_cg = { "weapon_reload_time_ak_sopmpd_cg", "0.5", 0, 0.0f, NULL };
cvar_t weapon_reload_time_aug_esport = { "weapon_reload_time_aug_esport", "0.5", 0, 0.0f, NULL };
cvar_t weapon_reload_time_t77 = { "weapon_reload_time_t77", "0.5", 0, 0.0f, NULL };
cvar_t weapon_reload_time_t77_dual = { "weapon_reload_time_t77_dual", "0.5", 0, 0.0f, NULL };
cvar_t weapon_reload_time_apc = { "weapon_reload_time_apc", "0.5", 0, 0.0f, NULL };
cvar_t weapon_reload_time_fg42 = { "weapon_reload_time_fg42", "0.5", 0, 0.0f, NULL };
cvar_t weapon_reload_time_msbs = { "weapon_reload_time_msbs", "0.5", 0, 0.0f, NULL };
cvar_t weapon_reload_time_as50 = { "weapon_reload_time_as50", "0.5", 0, 0.0f, NULL };
cvar_t weapon_reload_time_m1887_w = { "weapon_reload_time_m1887_w", "0.5", 0, 0.0f, NULL };
cvar_t weapon_reload_time_pgm = { "weapon_reload_time_pgm", "0.5", 0, 0.0f, NULL };
cvar_t weapon_reload_time_ump = { "weapon_reload_time_ump", "0.5", 0, 0.0f, NULL };
cvar_t weapon_reload_time_sig = { "weapon_reload_time_sig", "0.5", 0, 0.0f, NULL };
cvar_t weapon_reload_time_spectre = { "weapon_reload_time_spectre", "0.5", 0, 0.0f, NULL };
cvar_t weapon_reload_time_tar = { "weapon_reload_time_tar21", "0.5", 0, 0.0f, NULL };
cvar_t weapon_reload_time_xm8 = { "weapon_reload_time_xm8", "0.5", 0, 0.0f, NULL };
cvar_t weapon_reload_time_water_gun = { "weapon_reload_time_watergun", "0.5", 0, 0.0f, NULL };//
cvar_t weapon_reload_time_colt_python = { "weapon_reload_time_colt_python", "0.5", 0, 0.0f, NULL };
cvar_t weapon_reload_time_deagle_dual = { "weapon_reload_time_deagle_dual", "0.5", 0, 0.0f, NULL };
cvar_t weapon_reload_time_dual_handgun = { "weapon_reload_time_dual_handgun", "0.5", 0, 0.0f, NULL };
cvar_t weapon_reload_time_raging_bull = { "weapon_reload_time_raging_bull", "0.5", 0, 0.0f, NULL };
cvar_t weapon_reload_time_deagle = { "weapon_reload_time_deagle", "0.5", 0, 0.0f, NULL };
cvar_t weapon_reload_time_k5 = { "weapon_reload_time_k5", "0.5", 0, 0.0f, NULL };
cvar_t weapon_reload_time_glock = { "weapon_reload_time_glock", "0.5", 0, 0.0f, NULL };

//TODO sight
cvar_t weapon_sight_ak47 = { "weapon_sight_ak47", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t weapon_sight_aksopmod = { "weapon_sight_aksopmod", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t weapon_sight_aug_hbar = { "weapon_sight_aug_hbar", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t weapon_sight_aug = { "weapon_sight_aug", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t weapon_sight_augblitz = { "weapon_sight_augblitz", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t weapon_sight_p90 = { "weapon_sight_p90", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t weapon_sight_aug_a3_silencer = { "weapon_sight_aug_silencer", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t weapon_sight_f2000 = { "weapon_sight_f2000", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t weapon_sight_famas_g2 = { "weapon_sight_famas_g2", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t weapon_sight_g36c = { "weapon_sight_g36c", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t weapon_sight_k1 = { "weapon_sight_k1", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t weapon_sight_k2 = { "weapon_sight_k2", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t weapon_sight_kriss_sv = { "weapon_sight_kriss_sv", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t weapon_sight_kriss_sv_dual = { "weapon_sight_kriss_sv_dual", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t weapon_sight_kriss_sv_silencer = { "weapon_sight_kriss_sv_silencer", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t weapon_sight_kriss_sv_silencer_dual = { "weapon_sight_kriss_sv_silencer_dual", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t weapon_sight_m4_cqb_lv1 = { "weapon_sight_m4_cqb_lv1", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t weapon_sight_m4_cqb_lv2 = { "weapon_sight_m4_cqb_lv2", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t weapon_sight_m4a1 = { "weapon_sight_m4a1", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t weapon_sight_m4a1_s = { "weapon_sight_m4a1_s", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t weapon_sight_mp7 = { "weapon_sight_mp7", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t weapon_sight_oa93 = { "weapon_sight_oa93", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t weapon_sight_oa93_dual = { "weapon_sight_oa93_dual", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t weapon_sight_p90_mc = { "weapon_sight_p90_mc", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t weapon_sight_pindad_ss2_v5 = { "weapon_sight_pindad_ss2_v5", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t weapon_sight_groza = { "weapon_sight_groza", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t weapon_sight_sc2010 = { "weapon_sight_sc2010", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t weapon_sight_scar_carbine = { "weapon_sight_scar_carbine", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t weapon_sight_kriss_sv_crb = { "weapon_sight_kriss_sv_crb", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t weapon_sight_kriss_sv_crb_dual = { "weapon_sight_kriss_sv_crb_dual", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t weapon_sight_mp5k = { "weapon_sight_mp5k", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t weapon_sight_m4_azure = { "weapon_sight_m4_azure", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t weapon_sight_mp9 = { "weapon_sight_mp9", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t weapon_sight_sg550 = { "weapon_sight_sg550", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t weapon_sight_l115a1 = { "weapon_sight_l115a1", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t weapon_sight_cheytac_m200 = { "weapon_sight_cheytac_m200", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t weapon_sight_dragunov = { "weapon_sight_dragunov", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t weapon_sight_kar98k = { "weapon_sight_kar98k", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t weapon_sight_rangemaster_338 = { "weapon_sight_rangemaster_338", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t weapon_sight_m82a1 = { "weapon_sight_m82a1", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t weapon_sight_tactilite_t2 = { "weapon_sight_tactilite_t2", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t weapon_sight_ssg69 = { "weapon_sight_ssg69", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t weapon_sight_m4_spr_lv1 = { "weapon_sight_m4_spr_lv1", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t weapon_sight_m4_spr_lv2 = { "weapon_sight_m4_spr_lv2", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t weapon_sight_m1887 = { "weapon_sight_m1887", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t weapon_sight_spas_15 = { "weapon_sight_spas_15", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t weapon_sight_zombie_s = { "weapon_sight_zombie_s", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t weapon_sight_870mcs = { "weapon_sight_870mcs", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t weapon_sight_ak_sopmod_cg = { "weapon_sight_ak_sopmpd_cg", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t weapon_sight_aug_esport = { "weapon_sight_aug_esport", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t weapon_sight_t77 = { "weapon_sight_t77", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t weapon_sight_t77_dual = { "weapon_sight_t77_dual", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t weapon_sight_apc = { "weapon_sight_apc", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t weapon_sight_fg42 = { "weapon_sight_fg42", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t weapon_sight_msbs = { "weapon_sight_msbs", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t weapon_sight_as50 = { "weapon_sight_as50", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t weapon_sight_m1887_w = { "weapon_sight_m1887_w", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t weapon_sight_pgm = { "weapon_sight_pgm", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t weapon_sight_ump = { "weapon_sight_ump", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t weapon_sight_sig = { "weapon_sight_sig", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t weapon_sight_spectre = { "weapon_sight_spectre", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t weapon_sight_tar = { "weapon_sight_tar21", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t weapon_sight_xm8 = { "weapon_sight_xm8", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t weapon_sight_water_gun = { "weapon_sight_watergun", "0", FCVAR_SERVER, 0.0f, NULL };//
cvar_t weapon_sight_colt_python = { "weapon_sight_colt_python", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t weapon_sight_deagle_dual = { "weapon_sight_deagle_dual", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t weapon_sight_dual_handgun = { "weapon_sight_dual_handgun", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t weapon_sight_raging_bull = { "weapon_sight_raging_bull", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t weapon_sight_deagle = { "weapon_sight_deagle", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t weapon_sight_k5 = { "weapon_sight_k5", "0", FCVAR_SERVER, 0.0f, NULL };
cvar_t weapon_sight_glock = { "weapon_sight_glock", "0", FCVAR_SERVER, 0.0f, NULL };



cvar_t weapon_sound_ak47 = { "weapon_sound_ak47", "weapons/ak_sopmod-1.wav",NULL, 0.0f, NULL };
cvar_t weapon_sound_aksopmod = { "weapon_sound_aksopmod", "weapons/ak_sopmod-1.wav",FCVAR_SERVER, 0.0f, NULL };
cvar_t weapon_sound_aug_hbar = { "weapon_sound_aug_hbar", "weapons/ak_sopmod-1.wav",NULL, 0.0f, NULL };
cvar_t weapon_sound_aug = { "weapon_sound_aug", "weapons/ak_sopmod-1.wav",NULL, 0.0f, NULL };
cvar_t weapon_sound_augblitz = { "weapon_sound_augblitz", "weapons/ak_sopmod-1.wav",NULL, 0.0f, NULL };
cvar_t weapon_sound_p90 = { "weapon_sound_p90", "weapons/ak_sopmod-1.wav",NULL, 0.0f, NULL };
cvar_t weapon_sound_aug_a3_silencer = { "weapon_sound_aug_silencer", "weapons/ak_sopmod-1.wav",NULL, 0.0f, NULL };
cvar_t weapon_sound_f2000 = { "weapon_sound_f2000", "weapons/ak_sopmod-1.wav",NULL, 0.0f, NULL };
cvar_t weapon_sound_famas_g2 = { "weapon_sound_famas_g2", "weapons/ak_sopmod-1.wav",NULL, 0.0f, NULL };
cvar_t weapon_sound_g36c = { "weapon_sound_g36c", "weapons/ak_sopmod-1.wav",NULL, 0.0f, NULL };
cvar_t weapon_sound_k1 = { "weapon_sound_k1", "weapons/ak_sopmod-1.wav",NULL, 0.0f, NULL };
cvar_t weapon_sound_k2 = { "weapon_sound_k2", "weapons/ak_sopmod-1.wav",NULL, 0.0f, NULL };
cvar_t weapon_sound_kriss_sv = { "weapon_sound_kriss_sv", "weapons/ak_sopmod-1.wav",NULL, 0.0f, NULL };
cvar_t weapon_sound_kriss_sv_dual = { "weapon_sound_kriss_sv_dual", "weapons/ak_sopmod-1.wav",NULL, 0.0f, NULL };
cvar_t weapon_sound_kriss_sv_silencer = { "weapon_sound_kriss_sv_silencer", "weapons/ak_sopmod-1.wav",NULL, 0.0f, NULL };
cvar_t weapon_sound_kriss_sv_silencer_dual = { "weapon_sound_kriss_sv_silencer_dual", "weapons/ak_sopmod-1.wav",NULL, 0.0f, NULL };
cvar_t weapon_sound_m4_cqb_lv1 = { "weapon_sound_m4_cqb_lv1", "weapons/ak_sopmod-1.wav",NULL, 0.0f, NULL };
cvar_t weapon_sound_m4_cqb_lv2 = { "weapon_sound_m4_cqb_lv2", "weapons/ak_sopmod-1.wav",NULL, 0.0f, NULL };
cvar_t weapon_sound_m4a1 = { "weapon_sound_m4a1", "weapons/ak_sopmod-1.wav",NULL, 0.0f, NULL };
cvar_t weapon_sound_m4a1_s = { "weapon_sound_m4a1_s", "weapons/ak_sopmod-1.wav",NULL, 0.0f, NULL };
cvar_t weapon_sound_mp7 = { "weapon_sound_mp7", "weapons/ak_sopmod-1.wav",NULL, 0.0f, NULL };
cvar_t weapon_sound_oa93 = { "weapon_sound_oa93", "weapons/ak_sopmod-1.wav",NULL, 0.0f, NULL };
cvar_t weapon_sound_oa93_dual = { "weapon_sound_oa93_dual", "weapons/ak_sopmod-1.wav",NULL, 0.0f, NULL };
cvar_t weapon_sound_p90_mc = { "weapon_sound_p90_mc", "weapons/ak_sopmod-1.wav",NULL, 0.0f, NULL };
cvar_t weapon_sound_pindad_ss2_v5 = { "weapon_sound_pindad_ss2_v5", "weapons/ak_sopmod-1.wav",NULL, 0.0f, NULL };
cvar_t weapon_sound_groza = { "weapon_sound_groza", "weapons/ak_sopmod-1.wav",NULL, 0.0f, NULL };
cvar_t weapon_sound_sc2010 = { "weapon_sound_sc2010", "weapons/ak_sopmod-1.wav",NULL, 0.0f, NULL };
cvar_t weapon_sound_scar_carbine = { "weapon_sound_scar_carbine", "weapons/ak_sopmod-1.wav",NULL, 0.0f, NULL };
cvar_t weapon_sound_kriss_sv_crb = { "weapon_sound_kriss_sv_crb", "weapons/ak_sopmod-1.wav",NULL, 0.0f, NULL };
cvar_t weapon_sound_kriss_sv_crb_dual = { "weapon_sound_kriss_sv_crb_dual", "weapons/ak_sopmod-1.wav",NULL, 0.0f, NULL };
cvar_t weapon_sound_mp5k = { "weapon_sound_mp5k", "weapons/ak_sopmod-1.wav",NULL, 0.0f, NULL };
cvar_t weapon_sound_m4_azure = { "weapon_sound_m4_azure", "weapons/ak_sopmod-1.wav",NULL, 0.0f, NULL };
cvar_t weapon_sound_mp9 = { "weapon_sound_mp9", "weapons/ak_sopmod-1.wav",NULL, 0.0f, NULL };
cvar_t weapon_sound_sg550 = { "weapon_sound_sg550", "weapons/ak_sopmod-1.wav",NULL, 0.0f, NULL };
cvar_t weapon_sound_l115a1 = { "weapon_sound_l115a1", "weapons/ak_sopmod-1.wav",NULL, 0.0f, NULL };
cvar_t weapon_sound_cheytac_m200 = { "weapon_sound_cheytac_m200", "weapons/ak_sopmod-1.wav",NULL, 0.0f, NULL };
cvar_t weapon_sound_dragunov = { "weapon_sound_dragunov", "weapons/ak_sopmod-1.wav",NULL, 0.0f, NULL };
cvar_t weapon_sound_kar98k = { "weapon_sound_kar98k", "weapons/ak_sopmod-1.wav",NULL, 0.0f, NULL };
cvar_t weapon_sound_rangemaster_338 = { "weapon_sound_rangemaster_338", "weapons/ak_sopmod-1.wav",NULL, 0.0f, NULL };
cvar_t weapon_sound_m82a1 = { "weapon_sound_m82a1", "weapons/ak_sopmod-1.wav",NULL, 0.0f, NULL };
cvar_t weapon_sound_tactilite_t2 = { "weapon_sound_tactilite_t2", "weapons/ak_sopmod-1.wav",NULL, 0.0f, NULL };
cvar_t weapon_sound_ssg69 = { "weapon_sound_ssg69", "weapons/ak_sopmod-1.wav",NULL, 0.0f, NULL };
cvar_t weapon_sound_m4_spr_lv1 = { "weapon_sound_m4_spr_lv1", "weapons/ak_sopmod-1.wav",NULL, 0.0f, NULL };
cvar_t weapon_sound_m4_spr_lv2 = { "weapon_sound_m4_spr_lv2", "weapons/ak_sopmod-1.wav",NULL, 0.0f, NULL };
cvar_t weapon_sound_m1887 = { "weapon_sound_m1887", "weapons/ak_sopmod-1.wav",NULL, 0.0f, NULL };
cvar_t weapon_sound_spas_15 = { "weapon_sound_spas_15", "weapons/ak_sopmod-1.wav",NULL, 0.0f, NULL };
cvar_t weapon_sound_zombie_s = { "weapon_sound_zombie_s", "weapons/ak_sopmod-1.wav",NULL, 0.0f, NULL };
cvar_t weapon_sound_870mcs = { "weapon_sound_870mcs", "weapons/ak_sopmod-1.wav",NULL, 0.0f, NULL };
cvar_t weapon_sound_ak_sopmod_cg = { "weapon_sound_ak_sopmpd_cg", "weapons/ak_sopmod-1.wav",NULL, 0.0f, NULL };
cvar_t weapon_sound_aug_esport = { "weapon_sound_aug_esport", "weapons/ak_sopmod-1.wav",NULL, 0.0f, NULL };
cvar_t weapon_sound_t77 = { "weapon_sound_t77", "weapons/ak_sopmod-1.wav",NULL, 0.0f, NULL };
cvar_t weapon_sound_t77_dual = { "weapon_sound_t77_dual", "weapons/ak_sopmod-1.wav",NULL, 0.0f, NULL };
cvar_t weapon_sound_apc = { "weapon_sound_apc", "weapons/ak_sopmod-1.wav",NULL, 0.0f, NULL };
cvar_t weapon_sound_fg42 = { "weapon_sound_fg42", "weapons/ak_sopmod-1.wav",NULL, 0.0f, NULL };
cvar_t weapon_sound_msbs = { "weapon_sound_msbs", "weapons/ak_sopmod-1.wav",NULL, 0.0f, NULL };
cvar_t weapon_sound_as50 = { "weapon_sound_as50", "weapons/ak_sopmod-1.wav",NULL, 0.0f, NULL };
cvar_t weapon_sound_m1887_w = { "weapon_sound_m1887_w", "weapons/ak_sopmod-1.wav",NULL, 0.0f, NULL };
cvar_t weapon_sound_pgm = { "weapon_sound_pgm", "weapons/ak_sopmod-1.wav",NULL, 0.0f, NULL };
cvar_t weapon_sound_ump = { "weapon_sound_ump", "weapons/ak_sopmod-1.wav",NULL, 0.0f, NULL };
cvar_t weapon_sound_sig = { "weapon_sound_sig", "weapons/ak_sopmod-1.wav",NULL, 0.0f, NULL };
cvar_t weapon_sound_spectre = { "weapon_sound_spectre", "weapons/ak_sopmod-1.wav",NULL, 0.0f, NULL };
cvar_t weapon_sound_tar = { "weapon_sound_tar21", "weapons/ak_sopmod-1.wav",NULL, 0.0f, NULL };
cvar_t weapon_sound_xm8 = { "weapon_sound_xm8", "weapons/ak_sopmod-1.wav",NULL, 0.0f, NULL };
cvar_t weapon_sound_water_gun = { "weapon_sound_watergun", "weapons/ak_sopmod-1.wav",NULL, 0.0f, NULL };//
cvar_t weapon_sound_colt_python = { "weapon_sound_colt_python", "weapons/ak_sopmod-1.wav",NULL, 0.0f, NULL };
cvar_t weapon_sound_deagle_dual = { "weapon_sound_deagle_dual", "weapons/ak_sopmod-1.wav",NULL, 0.0f, NULL };
cvar_t weapon_sound_dual_handgun = { "weapon_sound_dual_handgun", "weapons/ak_sopmod-1.wav",NULL, 0.0f, NULL };
cvar_t weapon_sound_raging_bull = { "weapon_sound_raging_bull", "weapons/ak_sopmod-1.wav",NULL, 0.0f, NULL };
cvar_t weapon_sound_deagle = { "weapon_sound_deagle", "weapons/ak_sopmod-1.wav",NULL, 0.0f, NULL };
cvar_t weapon_sound_k5 = { "weapon_sound_k5", "weapons/ak_sopmod-1.wav",NULL, 0.0f, NULL };
cvar_t weapon_sound_glock = { "weapon_sound_glock", "weapons/ak_sopmod-1.wav",NULL, 0.0f, NULL };

cvar_t sv_unlimited_reserve_ammo =  { "sv_unlimited_reserve_ammo", "0", FCVAR_SERVER, 0.0f, NULL };

extern void Bot_RegisterCvars();
extern void Tutor_RegisterCVars();
extern void Hostage_RegisterCVars();

void EXT_FUNC GameDLLInit()
{
	//g_bIsCzeroGame = UTIL_IsGame("czero");
	g_bIsCzeroGame = true;
	g_bEnableCSBot = g_bIsCzeroGame || ENG_CHECK_PARM (const_cast<char *>("-bots"), nullptr) != 0;

	g_psv_gravity = CVAR_GET_POINTER("sv_gravity");
	g_psv_aim = CVAR_GET_POINTER("sv_aim");
	g_footsteps = CVAR_GET_POINTER("mp_footsteps");
	g_psv_accelerate = CVAR_GET_POINTER("sv_accelerate");
	g_psv_friction = CVAR_GET_POINTER("sv_friction");
	g_psv_stopspeed = CVAR_GET_POINTER("sv_stopspeed");

	CVAR_REGISTER(&displaysoundlist);
	CVAR_REGISTER(&timelimit);
	CVAR_REGISTER(&friendlyfire);
	CVAR_REGISTER(&flashlight);
	CVAR_REGISTER(&decalfrequency);
	CVAR_REGISTER(&allowmonsters);
	CVAR_REGISTER(&roundtime);
	CVAR_REGISTER(&buytime);
	CVAR_REGISTER(&freezetime);
	CVAR_REGISTER(&c4timer);
	CVAR_REGISTER(&ghostfrequency);
	CVAR_REGISTER(&autokick);
	CVAR_REGISTER(&autokick_timeout);
	CVAR_REGISTER(&restartround);
	CVAR_REGISTER(&sv_restart);
	CVAR_REGISTER(&limitteams);
	CVAR_REGISTER(&autoteambalance);
	CVAR_REGISTER(&tkpunish);
	CVAR_REGISTER(&hostagepenalty);
	CVAR_REGISTER(&mirrordamage);
	CVAR_REGISTER(&logmessages);
	CVAR_REGISTER(&forcecamera);
	CVAR_REGISTER(&forcechasecam);
	CVAR_REGISTER(&mapvoteratio);
	CVAR_REGISTER(&maxrounds);
	CVAR_REGISTER(&winlimit);
	CVAR_REGISTER(&windifference);
	CVAR_REGISTER(&fadetoblack);
	CVAR_REGISTER(&logdetail);
	CVAR_REGISTER(&startmoney);
	CVAR_REGISTER(&playerid);
	CVAR_REGISTER(&allow_spectators);
	CVAR_REGISTER(&mp_chattime);
	CVAR_REGISTER(&kick_percent);
CVAR_REGISTER(&pbhithuman);
CVAR_REGISTER(&cl_delaykill);
CVAR_REGISTER(&annhs);
CVAR_REGISTER(&tracer);
	CVAR_REGISTER(&fragsleft);
	CVAR_REGISTER(&timeleft);
	CVAR_REGISTER(&humans_join_team);

	CVAR_REGISTER(&gamemode);
	CVAR_REGISTER(&maxkills);
	CVAR_REGISTER(&sv_unlimited_reserve_ammo);

////////
CVAR_REGISTER(&weapon_damage_game_ak47);  
CVAR_REGISTER(&weapon_damage_game_aksopmod);
CVAR_REGISTER(&weapon_damage_game_aug_hbar);  
CVAR_REGISTER(&weapon_damage_game_aug);
CVAR_REGISTER(&weapon_damage_game_augblitz);
CVAR_REGISTER(&weapon_damage_game_p90);
CVAR_REGISTER(&weapon_damage_game_aug_a3_silencer);
CVAR_REGISTER(&weapon_damage_game_f2000);
CVAR_REGISTER(&weapon_damage_game_famas_g2);
CVAR_REGISTER(&weapon_damage_game_g36c);
CVAR_REGISTER(&weapon_damage_game_k1);
CVAR_REGISTER(&weapon_damage_game_k2);
CVAR_REGISTER(&weapon_damage_game_kriss_sv);
CVAR_REGISTER(&weapon_damage_game_kriss_sv_dual);
CVAR_REGISTER(&weapon_damage_game_kriss_sv_silencer);
CVAR_REGISTER(&weapon_damage_game_kriss_sv_silencer_dual);
CVAR_REGISTER(&weapon_damage_game_m4_cqb_lv1);
CVAR_REGISTER(&weapon_damage_game_m4_cqb_lv2);
CVAR_REGISTER(&weapon_damage_game_m4a1);
CVAR_REGISTER(&weapon_damage_game_m4a1_s); 
CVAR_REGISTER(&weapon_damage_game_mp7); 
CVAR_REGISTER(&weapon_damage_game_oa93);  
CVAR_REGISTER(&weapon_damage_game_oa93_dual);
CVAR_REGISTER(&weapon_damage_game_p90_mc); 
CVAR_REGISTER(&weapon_damage_game_pindad_ss2_v5);
CVAR_REGISTER(&weapon_damage_game_groza);
CVAR_REGISTER(&weapon_damage_game_sc2010);
CVAR_REGISTER(&weapon_damage_game_scar_carbine); 
CVAR_REGISTER(&weapon_damage_game_kriss_sv_crb); 
CVAR_REGISTER(&weapon_damage_game_kriss_sv_crb_dual); 
CVAR_REGISTER(&weapon_damage_game_mp5k); 
CVAR_REGISTER(&weapon_damage_game_m4_azure);  
CVAR_REGISTER(&weapon_damage_game_mp9);
CVAR_REGISTER(&weapon_damage_game_sg550);
CVAR_REGISTER(&weapon_damage_game_l115a1); 
CVAR_REGISTER(&weapon_damage_game_cheytac_m200); 
CVAR_REGISTER(&weapon_damage_game_dragunov);
CVAR_REGISTER(&weapon_damage_game_kar98k); 
CVAR_REGISTER(&weapon_damage_game_rangemaster_338);
CVAR_REGISTER(&weapon_damage_game_m82a1); 
CVAR_REGISTER(&weapon_damage_game_tactilite_t2); 
CVAR_REGISTER(&weapon_damage_game_ssg69); 
CVAR_REGISTER(&weapon_damage_game_m4_spr_lv1); 
CVAR_REGISTER(&weapon_damage_game_m4_spr_lv2);
CVAR_REGISTER(&weapon_damage_game_m1887);
CVAR_REGISTER(&weapon_damage_game_spas_15); 
CVAR_REGISTER(&weapon_damage_game_zombie_s);
CVAR_REGISTER(&weapon_damage_game_870mcs); 
CVAR_REGISTER(&weapon_damage_game_ak_sopmod_cg);
CVAR_REGISTER(&weapon_damage_game_aug_esport); 
CVAR_REGISTER(&weapon_damage_game_t77);
CVAR_REGISTER(&weapon_damage_game_t77_dual);
CVAR_REGISTER(&weapon_damage_game_apc);
CVAR_REGISTER(&weapon_damage_game_fg42);
CVAR_REGISTER(&weapon_damage_game_msbs); 
CVAR_REGISTER(&weapon_damage_game_as50); 
CVAR_REGISTER(&weapon_damage_game_m1887_w);  
CVAR_REGISTER(&weapon_damage_game_pgm); 
CVAR_REGISTER(&weapon_damage_game_ump); 
CVAR_REGISTER(&weapon_damage_game_sig);
CVAR_REGISTER(&weapon_damage_game_spectre); 
CVAR_REGISTER(&weapon_damage_game_tar); 
CVAR_REGISTER(&weapon_damage_game_xm8);
CVAR_REGISTER(&weapon_damage_game_water_gun); 
CVAR_REGISTER(&weapon_damage_game_colt_python); 
CVAR_REGISTER(&weapon_damage_game_deagle_dual);
CVAR_REGISTER(&weapon_damage_game_dual_handgun);
CVAR_REGISTER(&weapon_damage_game_raging_bull); 
CVAR_REGISTER(&weapon_damage_game_deagle);
CVAR_REGISTER(&weapon_damage_game_k5);
CVAR_REGISTER(&weapon_damage_game_glock);

//draw
CVAR_REGISTER(&weapon_draw_time_ak47);
CVAR_REGISTER(&weapon_draw_time_aksopmod);
CVAR_REGISTER(&weapon_draw_time_aug_hbar);
CVAR_REGISTER(&weapon_draw_time_aug);
CVAR_REGISTER(&weapon_draw_time_augblitz); 
CVAR_REGISTER(&weapon_draw_time_p90); 
CVAR_REGISTER(&weapon_draw_time_aug_a3_silencer); 
CVAR_REGISTER(&weapon_draw_time_f2000); 
CVAR_REGISTER(&weapon_draw_time_famas_g2); 
CVAR_REGISTER(&weapon_draw_time_g36c); 
CVAR_REGISTER(&weapon_draw_time_k1);
CVAR_REGISTER(&weapon_draw_time_k2);
CVAR_REGISTER(&weapon_draw_time_kriss_sv);
CVAR_REGISTER(&weapon_draw_time_kriss_sv_dual); 
CVAR_REGISTER(&weapon_draw_time_kriss_sv_silencer);
CVAR_REGISTER(&weapon_draw_time_kriss_sv_silencer_dual); 
CVAR_REGISTER(&weapon_draw_time_m4_cqb_lv1);
CVAR_REGISTER(&weapon_draw_time_m4_cqb_lv2); 
CVAR_REGISTER(&weapon_draw_time_m4a1);
CVAR_REGISTER(&weapon_draw_time_m4a1_s); 
CVAR_REGISTER(&weapon_draw_time_mp7);
CVAR_REGISTER(&weapon_draw_time_oa93); 
CVAR_REGISTER(&weapon_draw_time_oa93_dual);
CVAR_REGISTER(&weapon_draw_time_p90_mc); 
CVAR_REGISTER(&weapon_draw_time_pindad_ss2_v5);
CVAR_REGISTER(&weapon_draw_time_groza); 
CVAR_REGISTER(&weapon_draw_time_sc2010); 
CVAR_REGISTER(&weapon_draw_time_scar_carbine); 
CVAR_REGISTER(&weapon_draw_time_kriss_sv_crb);
CVAR_REGISTER(&weapon_draw_time_kriss_sv_crb_dual);
CVAR_REGISTER(&weapon_draw_time_mp5k); 
CVAR_REGISTER(&weapon_draw_time_m4_azure); 
CVAR_REGISTER(&weapon_draw_time_mp9); 
CVAR_REGISTER(&weapon_draw_time_sg550); 
CVAR_REGISTER(&weapon_draw_time_l115a1); 
CVAR_REGISTER(&weapon_draw_time_cheytac_m200);  
CVAR_REGISTER(&weapon_draw_time_dragunov);
CVAR_REGISTER(&weapon_draw_time_kar98k);
CVAR_REGISTER(&weapon_draw_time_rangemaster_338);
CVAR_REGISTER(&weapon_draw_time_m82a1);
CVAR_REGISTER(&weapon_draw_time_tactilite_t2); 
CVAR_REGISTER(&weapon_draw_time_ssg69); 
CVAR_REGISTER(&weapon_draw_time_m4_spr_lv1); 
CVAR_REGISTER(&weapon_draw_time_m4_spr_lv2); 
CVAR_REGISTER(&weapon_draw_time_m1887); 
CVAR_REGISTER(&weapon_draw_time_spas_15); 
CVAR_REGISTER(&weapon_draw_time_zombie_s);  
CVAR_REGISTER(&weapon_draw_time_870mcs); 
CVAR_REGISTER(&weapon_draw_time_ak_sopmod_cg); 
CVAR_REGISTER(&weapon_draw_time_aug_esport); 
CVAR_REGISTER(&weapon_draw_time_t77);
CVAR_REGISTER(&weapon_draw_time_t77_dual); 
CVAR_REGISTER(&weapon_draw_time_apc); 
CVAR_REGISTER(&weapon_draw_time_fg42); 
CVAR_REGISTER(&weapon_draw_time_msbs); 
CVAR_REGISTER(&weapon_draw_time_as50); 
CVAR_REGISTER(&weapon_draw_time_m1887_w); 
CVAR_REGISTER(&weapon_draw_time_pgm); 
CVAR_REGISTER(&weapon_draw_time_ump);
CVAR_REGISTER(&weapon_draw_time_sig); 
CVAR_REGISTER(&weapon_draw_time_spectre); 
CVAR_REGISTER(&weapon_draw_time_tar);  
CVAR_REGISTER(&weapon_draw_time_xm8); 
CVAR_REGISTER(&weapon_draw_time_water_gun);
CVAR_REGISTER(&weapon_draw_time_colt_python);
CVAR_REGISTER(&weapon_draw_time_deagle_dual); 
CVAR_REGISTER(&weapon_draw_time_dual_handgun);
CVAR_REGISTER(&weapon_draw_time_raging_bull);
CVAR_REGISTER(&weapon_draw_time_deagle);
CVAR_REGISTER(&weapon_draw_time_k5);
CVAR_REGISTER(&weapon_draw_time_glock); 

//reload
CVAR_REGISTER(&weapon_reload_time_ak47); 
CVAR_REGISTER(&weapon_reload_time_aksopmod); 
CVAR_REGISTER(&weapon_reload_time_aug_hbar);
CVAR_REGISTER(&weapon_reload_time_aug);  
CVAR_REGISTER(&weapon_reload_time_augblitz);
CVAR_REGISTER(&weapon_reload_time_p90); 
CVAR_REGISTER(&weapon_reload_time_aug_a3_silencer); 
CVAR_REGISTER(&weapon_reload_time_f2000);
CVAR_REGISTER(&weapon_reload_time_famas_g2);
CVAR_REGISTER(&weapon_reload_time_g36c);  
CVAR_REGISTER(&weapon_reload_time_k1); 
CVAR_REGISTER(&weapon_reload_time_k2); 
CVAR_REGISTER(&weapon_reload_time_kriss_sv); 
CVAR_REGISTER(&weapon_reload_time_kriss_sv_dual); 
CVAR_REGISTER(&weapon_reload_time_kriss_sv_silencer);
CVAR_REGISTER(&weapon_reload_time_kriss_sv_silencer_dual); 
CVAR_REGISTER(&weapon_reload_time_m4_cqb_lv1);  
CVAR_REGISTER(&weapon_reload_time_m4_cqb_lv2);
CVAR_REGISTER(&weapon_reload_time_m4a1);  
CVAR_REGISTER(&weapon_reload_time_m4a1_s); 
CVAR_REGISTER(&weapon_reload_time_mp7);
CVAR_REGISTER(&weapon_reload_time_oa93); 
CVAR_REGISTER(&weapon_reload_time_oa93_dual); 
CVAR_REGISTER(&weapon_reload_time_p90_mc);
CVAR_REGISTER(&weapon_reload_time_pindad_ss2_v5);  
CVAR_REGISTER(&weapon_reload_time_groza); 
CVAR_REGISTER(&weapon_reload_time_sc2010);
CVAR_REGISTER(&weapon_reload_time_scar_carbine); 
CVAR_REGISTER(&weapon_reload_time_kriss_sv_crb); 
CVAR_REGISTER(&weapon_reload_time_kriss_sv_crb_dual);
CVAR_REGISTER(&weapon_reload_time_mp5k); 
CVAR_REGISTER(&weapon_reload_time_m4_azure); 
CVAR_REGISTER(&weapon_reload_time_mp9);
CVAR_REGISTER(&weapon_reload_time_sg550);
CVAR_REGISTER(&weapon_reload_time_l115a1);
CVAR_REGISTER(&weapon_reload_time_cheytac_m200); 
CVAR_REGISTER(&weapon_reload_time_dragunov); 
CVAR_REGISTER(&weapon_reload_time_kar98k);
CVAR_REGISTER(&weapon_reload_time_rangemaster_338);
CVAR_REGISTER(&weapon_reload_time_m82a1); 
CVAR_REGISTER(&weapon_reload_time_tactilite_t2); 
CVAR_REGISTER(&weapon_reload_time_ssg69);  
CVAR_REGISTER(&weapon_reload_time_m4_spr_lv1);
CVAR_REGISTER(&weapon_reload_time_m4_spr_lv2);  
CVAR_REGISTER(&weapon_reload_time_m1887);
CVAR_REGISTER(&weapon_reload_time_spas_15); 
CVAR_REGISTER(&weapon_reload_time_zombie_s);  
CVAR_REGISTER(&weapon_reload_time_870mcs); 
CVAR_REGISTER(&weapon_reload_time_ak_sopmod_cg); 
CVAR_REGISTER(&weapon_reload_time_aug_esport); 
CVAR_REGISTER(&weapon_reload_time_t77);
CVAR_REGISTER(&weapon_reload_time_t77_dual); 
CVAR_REGISTER(&weapon_reload_time_apc);  
CVAR_REGISTER(&weapon_reload_time_fg42);
CVAR_REGISTER(&weapon_reload_time_msbs); 
CVAR_REGISTER(&weapon_reload_time_as50);
CVAR_REGISTER(&weapon_reload_time_m1887_w); 
CVAR_REGISTER(&weapon_reload_time_pgm); 
CVAR_REGISTER(&weapon_reload_time_ump); 
CVAR_REGISTER(&weapon_reload_time_sig);
CVAR_REGISTER(&weapon_reload_time_spectre); 
CVAR_REGISTER(&weapon_reload_time_tar); 
CVAR_REGISTER(&weapon_reload_time_xm8);
CVAR_REGISTER(&weapon_reload_time_water_gun); 
CVAR_REGISTER(&weapon_reload_time_colt_python);
CVAR_REGISTER(&weapon_reload_time_deagle_dual); 
CVAR_REGISTER(&weapon_reload_time_dual_handgun);
CVAR_REGISTER(&weapon_reload_time_raging_bull); 
CVAR_REGISTER(&weapon_reload_time_deagle);
CVAR_REGISTER(&weapon_reload_time_k5);
CVAR_REGISTER(&weapon_reload_time_glock);

//TODO sight
CVAR_REGISTER(&weapon_sight_ak47); 
CVAR_REGISTER(&weapon_sight_aksopmod);
CVAR_REGISTER(&weapon_sight_aug_hbar); 
CVAR_REGISTER(&weapon_sight_aug); 
CVAR_REGISTER(&weapon_sight_augblitz); 
CVAR_REGISTER(&weapon_sight_p90);
CVAR_REGISTER(&weapon_sight_aug_a3_silencer); 
CVAR_REGISTER(&weapon_sight_f2000);
CVAR_REGISTER(&weapon_sight_famas_g2);
CVAR_REGISTER(&weapon_sight_g36c);
CVAR_REGISTER(&weapon_sight_k1); 
CVAR_REGISTER(&weapon_sight_k2); 
CVAR_REGISTER(&weapon_sight_kriss_sv); 
CVAR_REGISTER(&weapon_sight_kriss_sv_dual); 
CVAR_REGISTER(&weapon_sight_kriss_sv_silencer);
CVAR_REGISTER(&weapon_sight_kriss_sv_silencer_dual);  
CVAR_REGISTER(&weapon_sight_m4_cqb_lv1); 
CVAR_REGISTER(&weapon_sight_m4_cqb_lv2); 
CVAR_REGISTER(&weapon_sight_m4a1);
CVAR_REGISTER(&weapon_sight_m4a1_s);
CVAR_REGISTER(&weapon_sight_mp7); 
CVAR_REGISTER(&weapon_sight_oa93); 
CVAR_REGISTER(&weapon_sight_oa93_dual);
CVAR_REGISTER(&weapon_sight_p90_mc);
CVAR_REGISTER(&weapon_sight_pindad_ss2_v5); 
CVAR_REGISTER(&weapon_sight_groza); 
CVAR_REGISTER(&weapon_sight_sc2010); 
CVAR_REGISTER(&weapon_sight_scar_carbine);
CVAR_REGISTER(&weapon_sight_kriss_sv_crb);
CVAR_REGISTER(&weapon_sight_kriss_sv_crb_dual);  
CVAR_REGISTER(&weapon_sight_mp5k);
CVAR_REGISTER(&weapon_sight_m4_azure); 
CVAR_REGISTER(&weapon_sight_mp9); 
CVAR_REGISTER(&weapon_sight_sg550);
CVAR_REGISTER(&weapon_sight_l115a1);
CVAR_REGISTER(&weapon_sight_cheytac_m200); 
CVAR_REGISTER(&weapon_sight_dragunov);
CVAR_REGISTER(&weapon_sight_kar98k);
CVAR_REGISTER(&weapon_sight_rangemaster_338);
CVAR_REGISTER(&weapon_sight_m82a1);
CVAR_REGISTER(&weapon_sight_tactilite_t2); 
CVAR_REGISTER(&weapon_sight_ssg69);
CVAR_REGISTER(&weapon_sight_m4_spr_lv1); 
CVAR_REGISTER(&weapon_sight_m4_spr_lv2);
CVAR_REGISTER(&weapon_sight_m1887); 
CVAR_REGISTER(&weapon_sight_spas_15); 
CVAR_REGISTER(&weapon_sight_zombie_s);
CVAR_REGISTER(&weapon_sight_870mcs);
CVAR_REGISTER(&weapon_sight_ak_sopmod_cg); 
CVAR_REGISTER(&weapon_sight_aug_esport); 
CVAR_REGISTER(&weapon_sight_t77); 
CVAR_REGISTER(&weapon_sight_t77_dual);
CVAR_REGISTER(&weapon_sight_apc);
CVAR_REGISTER(&weapon_sight_fg42); 
CVAR_REGISTER(&weapon_sight_msbs);
CVAR_REGISTER(&weapon_sight_as50); 
CVAR_REGISTER(&weapon_sight_m1887_w); 
CVAR_REGISTER(&weapon_sight_pgm);
CVAR_REGISTER(&weapon_sight_ump); 
CVAR_REGISTER(&weapon_sight_sig); 
CVAR_REGISTER(&weapon_sight_spectre);
CVAR_REGISTER(&weapon_sight_tar);
CVAR_REGISTER(&weapon_sight_xm8); 
CVAR_REGISTER(&weapon_sight_water_gun); 
CVAR_REGISTER(&weapon_sight_colt_python); 
CVAR_REGISTER(&weapon_sight_deagle_dual); 
CVAR_REGISTER(&weapon_sight_dual_handgun); 
CVAR_REGISTER(&weapon_sight_raging_bull);
CVAR_REGISTER(&weapon_sight_deagle);
CVAR_REGISTER(&weapon_sight_k5);  
CVAR_REGISTER(&weapon_sight_glock); 

CVAR_REGISTER(&weapon_sound_ak47);  
CVAR_REGISTER(&weapon_sound_aksopmod);
CVAR_REGISTER(&weapon_sound_aug_hbar);  
CVAR_REGISTER(&weapon_sound_aug);
CVAR_REGISTER(&weapon_sound_augblitz);
CVAR_REGISTER(&weapon_sound_p90);
CVAR_REGISTER(&weapon_sound_aug_a3_silencer);
CVAR_REGISTER(&weapon_sound_f2000);
CVAR_REGISTER(&weapon_sound_famas_g2);
CVAR_REGISTER(&weapon_sound_g36c);
CVAR_REGISTER(&weapon_sound_k1);
CVAR_REGISTER(&weapon_sound_k2);
CVAR_REGISTER(&weapon_sound_kriss_sv);
CVAR_REGISTER(&weapon_sound_kriss_sv_dual);
CVAR_REGISTER(&weapon_sound_kriss_sv_silencer);
CVAR_REGISTER(&weapon_sound_kriss_sv_silencer_dual);
CVAR_REGISTER(&weapon_sound_m4_cqb_lv1);
CVAR_REGISTER(&weapon_sound_m4_cqb_lv2);
CVAR_REGISTER(&weapon_sound_m4a1);
CVAR_REGISTER(&weapon_sound_m4a1_s); 
CVAR_REGISTER(&weapon_sound_mp7); 
CVAR_REGISTER(&weapon_sound_oa93);  
CVAR_REGISTER(&weapon_sound_oa93_dual);
CVAR_REGISTER(&weapon_sound_p90_mc); 
CVAR_REGISTER(&weapon_sound_pindad_ss2_v5);
CVAR_REGISTER(&weapon_sound_groza);
CVAR_REGISTER(&weapon_sound_sc2010);
CVAR_REGISTER(&weapon_sound_scar_carbine); 
CVAR_REGISTER(&weapon_sound_kriss_sv_crb); 
CVAR_REGISTER(&weapon_sound_kriss_sv_crb_dual); 
CVAR_REGISTER(&weapon_sound_mp5k); 
CVAR_REGISTER(&weapon_sound_m4_azure);  
CVAR_REGISTER(&weapon_sound_mp9);
CVAR_REGISTER(&weapon_sound_sg550);
CVAR_REGISTER(&weapon_sound_l115a1); 
CVAR_REGISTER(&weapon_sound_cheytac_m200); 
CVAR_REGISTER(&weapon_sound_dragunov);
CVAR_REGISTER(&weapon_sound_kar98k); 
CVAR_REGISTER(&weapon_sound_rangemaster_338);
CVAR_REGISTER(&weapon_sound_m82a1); 
CVAR_REGISTER(&weapon_sound_tactilite_t2); 
CVAR_REGISTER(&weapon_sound_ssg69); 
CVAR_REGISTER(&weapon_sound_m4_spr_lv1); 
CVAR_REGISTER(&weapon_sound_m4_spr_lv2);
CVAR_REGISTER(&weapon_sound_m1887);
CVAR_REGISTER(&weapon_sound_spas_15); 
CVAR_REGISTER(&weapon_sound_zombie_s);
CVAR_REGISTER(&weapon_sound_870mcs); 
CVAR_REGISTER(&weapon_sound_ak_sopmod_cg);
CVAR_REGISTER(&weapon_sound_aug_esport); 
CVAR_REGISTER(&weapon_sound_t77);
CVAR_REGISTER(&weapon_sound_t77_dual);
CVAR_REGISTER(&weapon_sound_apc);
CVAR_REGISTER(&weapon_sound_fg42);
CVAR_REGISTER(&weapon_sound_msbs); 
CVAR_REGISTER(&weapon_sound_as50); 
CVAR_REGISTER(&weapon_sound_m1887_w);  
CVAR_REGISTER(&weapon_sound_pgm); 
CVAR_REGISTER(&weapon_sound_ump); 
CVAR_REGISTER(&weapon_sound_sig);
CVAR_REGISTER(&weapon_sound_spectre); 
CVAR_REGISTER(&weapon_sound_tar); 
CVAR_REGISTER(&weapon_sound_xm8);
CVAR_REGISTER(&weapon_sound_water_gun); 
CVAR_REGISTER(&weapon_sound_colt_python); 
CVAR_REGISTER(&weapon_sound_deagle_dual);
CVAR_REGISTER(&weapon_sound_dual_handgun);
CVAR_REGISTER(&weapon_sound_raging_bull); 
CVAR_REGISTER(&weapon_sound_deagle);
CVAR_REGISTER(&weapon_sound_k5);
CVAR_REGISTER(&weapon_sound_glock);

	Bot_RegisterCvars();
	Tutor_RegisterCVars();
	Hostage_RegisterCVars();
}
