#include "extdll.h"
#include "util.h"
#include "cbase.h"
#include "player.h"
#include "monsters.h"
#include "weapons.h"

/*
* Globals initialization
*/
AutoBuyInfoStruct g_autoBuyInfo[] =
{
	{ AUTOBUYCLASS_PRIMARY|AUTOBUYCLASS_RIFLE,		"galil",	"weapon_groza" },
	{ AUTOBUYCLASS_PRIMARY|AUTOBUYCLASS_RIFLE,		"ak47",		"weapon_ak47" },
	{ AUTOBUYCLASS_PRIMARY|AUTOBUYCLASS_SNIPERRIFLE,	"scout",	"weapon_scout" },
	{ AUTOBUYCLASS_PRIMARY|AUTOBUYCLASS_SNIPERRIFLE,	"sg552",	"weapon_tactilite_t2" },
	{ AUTOBUYCLASS_PRIMARY|AUTOBUYCLASS_SNIPERRIFLE,	"awp",		"weapon_awp" },
	{ AUTOBUYCLASS_PRIMARY|AUTOBUYCLASS_SNIPERRIFLE,	"g3sg1",	"weapon_cheytac_m200" },
	{ AUTOBUYCLASS_PRIMARY|AUTOBUYCLASS_RIFLE,		"famas",	"weapon_mp7" },
	{ AUTOBUYCLASS_PRIMARY|AUTOBUYCLASS_RIFLE,		"m4a1",		"weapon_m4a1" },
	{ AUTOBUYCLASS_PRIMARY|AUTOBUYCLASS_RIFLE,		"aug",		"weapon_aug" },
	{ AUTOBUYCLASS_PRIMARY|AUTOBUYCLASS_RIFLE,		"sg550",	"weapon_sg550" },
	{ AUTOBUYCLASS_SECONDARY|AUTOBUYCLASS_PISTOL,		"glock",	"weapon_glock18" },
	{ AUTOBUYCLASS_SECONDARY|AUTOBUYCLASS_PISTOL,		"usp",		"weapon_usp" },
	{ AUTOBUYCLASS_SECONDARY|AUTOBUYCLASS_PISTOL,		"p228",		"weapon_python" },
	{ AUTOBUYCLASS_SECONDARY|AUTOBUYCLASS_PISTOL,		"deagle",	"weapon_deagle" },
	{ AUTOBUYCLASS_SECONDARY|AUTOBUYCLASS_PISTOL,		"elites",	"weapon_deagle_dual" },
	{ AUTOBUYCLASS_SECONDARY|AUTOBUYCLASS_PISTOL,		"fn57",		"weapon_taurus_raging_bull" },
	{ AUTOBUYCLASS_PRIMARY|AUTOBUYCLASS_SHOTGUN,		"m3",		"weapon_m3" },
	{ AUTOBUYCLASS_PRIMARY|AUTOBUYCLASS_SHOTGUN,		"m1887",		"weapon_m1887" },
	{ AUTOBUYCLASS_PRIMARY|AUTOBUYCLASS_SHOTGUN,		"xm1014",	"weapon_spas_15" },
	{ AUTOBUYCLASS_PRIMARY|AUTOBUYCLASS_SMG,		"mac10",	"weapon_oa93" },
	{ AUTOBUYCLASS_PRIMARY|AUTOBUYCLASS_SMG,		"tmp",		"weapon_kriss_sv" },
	{ AUTOBUYCLASS_PRIMARY|AUTOBUYCLASS_SMG,		"mp5",		"weapon_p90_mc" },
	{ AUTOBUYCLASS_PRIMARY|AUTOBUYCLASS_SMG,		"ump45",	"weapon_scar_carbine" },
	{ AUTOBUYCLASS_PRIMARY|AUTOBUYCLASS_SMG,		"p90",		"weapon_p90" },
	{ AUTOBUYCLASS_PRIMARY|AUTOBUYCLASS_MACHINEGUN,		"m249",		"weapon_g36c" },
	{ AUTOBUYCLASS_PRIMARY|AUTOBUYCLASS_AMMO,		"primammo",	"primammo" },
	{ AUTOBUYCLASS_SECONDARY|AUTOBUYCLASS_AMMO,		"secammo",	"secammo" },
	{ AUTOBUYCLASS_ARMOR,					"vest",		"item_kevlar" },
	{ AUTOBUYCLASS_ARMOR,					"vesthelm",	"item_assaultsuit" },
	{ AUTOBUYCLASS_GRENADE,					"flash",	"weapon_flashbang" },
	{ AUTOBUYCLASS_GRENADE,					"hegren",	"weapon_hegrenade" },
	{ AUTOBUYCLASS_GRENADE,					"sgren",	"weapon_smokegrenade"},
	{ AUTOBUYCLASS_NIGHTVISION,				"nvgs",		"nvgs" },
	{ AUTOBUYCLASS_DEFUSER,					"defuser",	"defuser" },
	{ AUTOBUYCLASS_PRIMARY|AUTOBUYCLASS_SHIELD,		"shield",	"rangemaster_338" },
	{ AUTOBUYCLASS_NONE, NULL, NULL }
};

WeaponAliasInfo weaponAliasInfo[] =
{
	{ "p228",	WEAPON_P228 },
	{ "???",	WEAPON_GLOCK },
	{ "scout",	WEAPON_SCOUT },
	{ "hegren",	WEAPON_HEGRENADE },
	{ "xm1014",	WEAPON_XM1014 },
	{ "c4",		WEAPON_C4 },
	{ "mac10",	WEAPON_MAC10 },
	{ "aug",	WEAPON_AUG },
	{ "sgren",	WEAPON_SMOKEGRENADE },
	{ "elites",	WEAPON_ELITE },
	{ "fn57",	WEAPON_FIVESEVEN },
	{ "ump45",	WEAPON_UMP45 },
	{ "sg550",	WEAPON_SG550 },
	{ "galil",	WEAPON_GALIL },
	{ "famas",	WEAPON_FAMAS },
	{ "usp",	WEAPON_USP },
	{ "glock",	WEAPON_GLOCK18 },
	{ "awp",	WEAPON_AWP },
	{ "mp5",	WEAPON_MP5N },
	{ "m249",	WEAPON_M249 },
	{ "m3",		WEAPON_M3 },
	{ "m1887",		WEAPON_M3 },
	{ "m4a1",	WEAPON_M4A1 },
	{ "tmp",	WEAPON_TMP },
	{ "g3sg1",	WEAPON_G3SG1 },
	{ "flash",	WEAPON_FLASHBANG },
	{ "deagle",	WEAPON_DEAGLE },
	{ "sg552",	WEAPON_SG552 },
	{ "ak47",	WEAPON_AK47 },
	{ "knife",	WEAPON_KNIFE },
	{ "p90",	WEAPON_P90 },
	{ "shield",	WEAPON_SHIELDGUN },
	{ "none",	WEAPON_NONE },
	{ "grenade",	WEAPON_HEGRENADE },
	{ "hegrenade",	WEAPON_HEGRENADE },
	{ "glock18",	WEAPON_GLOCK18 },
	{ "elite",	WEAPON_ELITE },
	{ "fiveseven",	WEAPON_FIVESEVEN },
	{ "mp5navy",	WEAPON_MP5N },
 	{ "custom1",	WEAPON_CUSTOM1 }, 	
 	{ "custom2",	WEAPON_CUSTOM2 }, 	
 	{ "custom3",	WEAPON_CUSTOM3 }, 	
 	{ "custom4",	WEAPON_CUSTOM4 }, 	
 	{ "custom5",	WEAPON_CUSTOM5 }, 	
 	{ "custom6",	WEAPON_CUSTOM6 }, 	
 	{ "custom7",	WEAPON_CUSTOM7 }, 	
 	{ "custom8",	WEAPON_CUSTOM8 }, 	
 	{ "custom9",	WEAPON_CUSTOM9 }, 	
 	{ "custom10",	WEAPON_CUSTOM10 }, 	
 	{ "custom11",	WEAPON_CUSTOM11 }, 	
 	{ "custom12",	WEAPON_CUSTOM12 }, 	
 	{ "custom13",	WEAPON_CUSTOM13 }, 	
 	{ "custom14",	WEAPON_CUSTOM14 }, 	
 	{ "custom15",	WEAPON_CUSTOM15 }, 	
 	{ "custom16",	WEAPON_CUSTOM16 }, 	
 	{ "custom17",	WEAPON_CUSTOM17 }, 	
 	{ "custom18",	WEAPON_CUSTOM18 }, 	
 	{ "custom19",	WEAPON_CUSTOM19 }, 	
 	{ "custom20",	WEAPON_CUSTOM20 }, 	
 	{ "custom21",	WEAPON_CUSTOM21 }, 	
 	{ "custom22",	WEAPON_CUSTOM22 }, 	
 	{ "custom23",	WEAPON_CUSTOM23 }, 	
 	{ "custom24",	WEAPON_CUSTOM24 }, 	
 	{ "custom25",	WEAPON_CUSTOM25 }, 	
 	{ "custom26",	WEAPON_CUSTOM26 }, 	
 	{ "custom27",	WEAPON_CUSTOM27 }, 	
 	{ "custom28",	WEAPON_CUSTOM28 }, 	
 	{ "custom29",	WEAPON_CUSTOM29 }, 	
 	{ "custom30",	WEAPON_CUSTOM30 }, 	
 	{ "custom31",	WEAPON_CUSTOM31 }, 	
 	{ "custom32",	WEAPON_CUSTOM32 }, 	
 	{ "custom33",	WEAPON_CUSTOM33 }, 	
 	{ "custom34",	WEAPON_CUSTOM34 }, 	
 	{ "custom35",	WEAPON_CUSTOM35 }, 	
 	{ "custom36",	WEAPON_CUSTOM36 }, 	
 	{ "custom37",	WEAPON_CUSTOM37 }, 	
 	{ "custom38",	WEAPON_CUSTOM38 }, 	
 	{ "custom39",	WEAPON_CUSTOM39 }, 	
 	{ "custom40",	WEAPON_CUSTOM40 }, 	
 	{ "custom41",	WEAPON_CUSTOM41 }, 	
 	{ "custom42",	WEAPON_CUSTOM42 }, 	
 	{ "custom43",	WEAPON_CUSTOM43 }, 	
 	{ "custom44",	WEAPON_CUSTOM44 }, 	
 	{ "custom45",	WEAPON_CUSTOM45 }, 	
 	{ "custom46",	WEAPON_CUSTOM46 }, 	
 	{ "custom47",	WEAPON_CUSTOM47 }, 	
 	{ "custom48",	WEAPON_CUSTOM48 }, 	
 	{ "custom49",	WEAPON_CUSTOM49 }, 	
 	{ "custom50",	WEAPON_CUSTOM50 }, 	
 	{ "custom51",	WEAPON_CUSTOM51 }, 	
 	{ "custom52",	WEAPON_CUSTOM52 }, 	
 	{ "custom53",	WEAPON_CUSTOM53 }, 	
 	{ "custom54",	WEAPON_CUSTOM54 }, 	
 	{ "custom55",	WEAPON_CUSTOM55 }, 	
 	{ "custom56",	WEAPON_CUSTOM56 }, 	
 	{ "custom57",	WEAPON_CUSTOM57 }, 	
 	{ "custom58",	WEAPON_CUSTOM58 }, 	
 	{ "custom59",	WEAPON_CUSTOM59 }, 	
 	{ "custom60",	WEAPON_CUSTOM60 }, 	
 	{ "custom61",	WEAPON_CUSTOM61 }, 	
 	{ "custom62",	WEAPON_CUSTOM62 }, 	
 	{ "custom63",	WEAPON_CUSTOM63 }, 	
 	{ "custom64",	WEAPON_CUSTOM64 }, 	
 	{ "custom65",	WEAPON_CUSTOM65 }, 	
 	{ "custom66",	WEAPON_CUSTOM66 }, 	
 	{ "custom67",	WEAPON_CUSTOM67 }, 	
 	{ "custom68",	WEAPON_CUSTOM68 }, 	
 	{ "custom69",	WEAPON_CUSTOM69 }, 	
 	{ "custom70",	WEAPON_CUSTOM70 }, 	
 	{ "custom71",	WEAPON_CUSTOM71 }, 	
 	{ "custom72",	WEAPON_CUSTOM72 }, 	
 	{ "custom73",	WEAPON_CUSTOM73 }, 	
 	{ "custom74",	WEAPON_CUSTOM74 }, 	
 	{ "custom75",	WEAPON_CUSTOM75 }, 	
 	{ "custom76",	WEAPON_CUSTOM76 }, 	
 	{ "custom77",	WEAPON_CUSTOM77 }, 	
 	{ "custom78",	WEAPON_CUSTOM78 }, 	
 	{ "custom79",	WEAPON_CUSTOM79 }, 	
 	{ "custom80",	WEAPON_CUSTOM80 }, 	
 	{ "custom81",	WEAPON_CUSTOM81 }, 	
 	{ "custom82",	WEAPON_CUSTOM82 }, 	
 	{ "custom83",	WEAPON_CUSTOM83 }, 	
 	{ "custom84",	WEAPON_CUSTOM84 }, 	
 	{ "custom85",	WEAPON_CUSTOM85 }, 	
 	{ "custom86",	WEAPON_CUSTOM86 }, 	
 	{ "custom87",	WEAPON_CUSTOM87 }, 	
 	{ "custom88",	WEAPON_CUSTOM88 }, 	
 	{ "custom89",	WEAPON_CUSTOM89 }, 	
 	{ "custom90",	WEAPON_CUSTOM90 }, 	
 	{ "custom91",	WEAPON_CUSTOM91 }, 	
 	{ "custom92",	WEAPON_CUSTOM92 }, 	
 	{ "custom93",	WEAPON_CUSTOM93 }, 	
 	{ "custom94",	WEAPON_CUSTOM94 }, 	
 	{ "custom95",	WEAPON_CUSTOM95 }, 	
 	{ "custom96",	WEAPON_CUSTOM96 }, 	
 	{ "custom97",	WEAPON_CUSTOM97 }, 	
 	{ "custom98",	WEAPON_CUSTOM98 }, 	
 	{ "custom99",	WEAPON_CUSTOM99 }, 	
 	{ "custom100",	WEAPON_CUSTOM100 }, 
	{ NULL,		WEAPON_NONE }
};

WeaponBuyAliasInfo weaponBuyAliasInfo[] =
{
	{ "galil",		WEAPON_GALIL,		"#Galil" },
	{ "defender",		WEAPON_GALIL,		"#Galil" },
	{ "ak47",		WEAPON_AK47,		"#AK47" },
	{ "cv47",		WEAPON_AK47,		"#AK47" },
	{ "scout",		WEAPON_SCOUT,		NULL },
	{ "sg552",		WEAPON_SG552,		"#SG552" },
	{ "krieg552",		WEAPON_SG552,		"#SG552" },
	{ "awp",		WEAPON_AWP,		NULL },
	{ "magnum",		WEAPON_AWP,		NULL },
	{ "g3sg1",		WEAPON_G3SG1,		"#G3SG1" },
	{ "d3au1",		WEAPON_G3SG1,		"#G3SG1" },
	{ "famas",		WEAPON_FAMAS,		"#Famas" },
	{ "clarion",		WEAPON_FAMAS,		"#Famas" },
	{ "m4a1",		WEAPON_M4A1,		"#M4A1" },
	{ "aug",		WEAPON_AUG,		"#Aug" },
	{ "bullpup",		WEAPON_AUG,		"#Aug" },
	{ "sg550",		WEAPON_SG550,		"#SG550" },
	{ "krieg550",		WEAPON_SG550,		"#SG550" },
	{ "glock",		WEAPON_GLOCK18,		NULL },
	{ "9x19mm",		WEAPON_GLOCK18,		NULL },
	{ "usp",		WEAPON_USP,		NULL },
	{ "km45",		WEAPON_USP,		NULL },
	{ "p228",		WEAPON_P228,		NULL },
	{ "228compact",		WEAPON_P228,		NULL },
	{ "deagle",		WEAPON_DEAGLE,		NULL },
	{ "nighthaw",		WEAPON_DEAGLE,		NULL },
	{ "elites",		WEAPON_ELITE,		"#Beretta96G" },
	{ "fn57",		WEAPON_FIVESEVEN,	"#FiveSeven" },
	{ "fiveseven",		WEAPON_FIVESEVEN,	"#FiveSeven" },
	{ "m3",			WEAPON_M3,		NULL },
	{ "12gauge",		WEAPON_M3,		NULL },
	{ "xm1014",		WEAPON_XM1014,		NULL },
	{ "autoshotgun",	WEAPON_XM1014,		NULL },
	{ "mac10",		WEAPON_MAC10,		"#Mac10" },
	{ "tmp",		WEAPON_TMP,		"#tmp" },
	{ "mp",			WEAPON_TMP,		"#tmp" },
	{ "mp5",		WEAPON_MP5N,		NULL },
	{ "smg",		WEAPON_MP5N,		NULL },
	{ "ump45",		WEAPON_UMP45,		NULL },
	{ "p90",		WEAPON_P90,		NULL },
	{ "c90",		WEAPON_P90,		NULL },
	{ "m249",		WEAPON_M249,		NULL },

 	{ "custom1",		WEAPON_CUSTOM1,		NULL }, 	
 	{ "custom2",		WEAPON_CUSTOM2,		NULL }, 	
 	{ "custom3",		WEAPON_CUSTOM3,		NULL }, 	
 	{ "custom4",		WEAPON_CUSTOM4,		NULL }, 	
 	{ "custom5",		WEAPON_CUSTOM5,		NULL }, 	
 	{ "custom6",		WEAPON_CUSTOM6,		NULL }, 	
 	{ "custom7",		WEAPON_CUSTOM7,		NULL }, 	
 	{ "custom8",		WEAPON_CUSTOM8,		NULL }, 	
 	{ "custom9",		WEAPON_CUSTOM9,		NULL }, 	
 	{ "custom10",		WEAPON_CUSTOM10,		NULL }, 	
 	{ "custom11",		WEAPON_CUSTOM11,		NULL }, 	
 	{ "custom12",		WEAPON_CUSTOM12,		NULL }, 	
 	{ "custom13",		WEAPON_CUSTOM13,		NULL }, 	
 	{ "custom14",		WEAPON_CUSTOM14,		NULL }, 	
 	{ "custom15",		WEAPON_CUSTOM15,		NULL }, 	
 	{ "custom16",		WEAPON_CUSTOM16,		NULL }, 	
 	{ "custom17",		WEAPON_CUSTOM17,		NULL }, 	
 	{ "custom18",		WEAPON_CUSTOM18,		NULL }, 	
 	{ "custom19",		WEAPON_CUSTOM19,		NULL }, 	
 	{ "custom20",		WEAPON_CUSTOM20,		NULL }, 	
 	{ "custom21",		WEAPON_CUSTOM21,		NULL }, 	
 	{ "custom22",		WEAPON_CUSTOM22,		NULL }, 	
 	{ "custom23",		WEAPON_CUSTOM23,		NULL }, 	
 	{ "custom24",		WEAPON_CUSTOM24,		NULL }, 	
 	{ "custom25",		WEAPON_CUSTOM25,		NULL }, 	
 	{ "custom26",		WEAPON_CUSTOM26,		NULL }, 	
 	{ "custom27",		WEAPON_CUSTOM27,		NULL }, 	
 	{ "custom28",		WEAPON_CUSTOM28,		NULL }, 	
 	{ "custom29",		WEAPON_CUSTOM29,		NULL }, 	
 	{ "custom30",		WEAPON_CUSTOM30,		NULL }, 	
 	{ "custom31",		WEAPON_CUSTOM31,		NULL }, 	
 	{ "custom32",		WEAPON_CUSTOM32,		NULL }, 	
 	{ "custom33",		WEAPON_CUSTOM33,		NULL }, 	
 	{ "custom34",		WEAPON_CUSTOM34,		NULL }, 	
 	{ "custom35",		WEAPON_CUSTOM35,		NULL }, 	
 	{ "custom36",		WEAPON_CUSTOM36,		NULL }, 	
 	{ "custom37",		WEAPON_CUSTOM37,		NULL }, 	
 	{ "custom38",		WEAPON_CUSTOM38,		NULL }, 	
 	{ "custom39",		WEAPON_CUSTOM39,		NULL }, 	
 	{ "custom40",		WEAPON_CUSTOM40,		NULL }, 	
 	{ "custom41",		WEAPON_CUSTOM41,		NULL }, 	
 	{ "custom42",		WEAPON_CUSTOM42,		NULL }, 	
 	{ "custom43",		WEAPON_CUSTOM43,		NULL }, 	
 	{ "custom44",		WEAPON_CUSTOM44,		NULL }, 	
 	{ "custom45",		WEAPON_CUSTOM45,		NULL }, 	
 	{ "custom46",		WEAPON_CUSTOM46,		NULL }, 	
 	{ "custom47",		WEAPON_CUSTOM47,		NULL }, 	
 	{ "custom48",		WEAPON_CUSTOM48,		NULL }, 	
 	{ "custom49",		WEAPON_CUSTOM49,		NULL }, 	
 	{ "custom50",		WEAPON_CUSTOM50,		NULL }, 	
 	{ "custom51",		WEAPON_CUSTOM51,		NULL }, 	
 	{ "custom52",		WEAPON_CUSTOM52,		NULL }, 	
 	{ "custom53",		WEAPON_CUSTOM53,		NULL }, 	
 	{ "custom54",		WEAPON_CUSTOM54,		NULL }, 	
 	{ "custom55",		WEAPON_CUSTOM55,		NULL }, 	
 	{ "custom56",		WEAPON_CUSTOM56,		NULL }, 	
 	{ "custom57",		WEAPON_CUSTOM57,		NULL }, 	
 	{ "custom58",		WEAPON_CUSTOM58,		NULL }, 	
 	{ "custom59",		WEAPON_CUSTOM59,		NULL }, 	
 	{ "custom60",		WEAPON_CUSTOM60,		NULL }, 	
 	{ "custom61",		WEAPON_CUSTOM61,		NULL }, 	
 	{ "custom62",		WEAPON_CUSTOM62,		NULL }, 	
 	{ "custom63",		WEAPON_CUSTOM63,		NULL }, 	
 	{ "custom64",		WEAPON_CUSTOM64,		NULL }, 	
 	{ "custom65",		WEAPON_CUSTOM65,		NULL }, 	
 	{ "custom66",		WEAPON_CUSTOM66,		NULL }, 	
 	{ "custom67",		WEAPON_CUSTOM67,		NULL }, 	
 	{ "custom68",		WEAPON_CUSTOM68,		NULL }, 	
 	{ "custom69",		WEAPON_CUSTOM69,		NULL }, 	
 	{ "custom70",		WEAPON_CUSTOM70,		NULL }, 	
 	{ "custom71",		WEAPON_CUSTOM71,		NULL }, 	
 	{ "custom72",		WEAPON_CUSTOM72,		NULL }, 	
 	{ "custom73",		WEAPON_CUSTOM73,		NULL }, 	
 	{ "custom74",		WEAPON_CUSTOM74,		NULL }, 	
 	{ "custom75",		WEAPON_CUSTOM75,		NULL }, 	
 	{ "custom76",		WEAPON_CUSTOM76,		NULL }, 	
 	{ "custom77",		WEAPON_CUSTOM77,		NULL }, 	
 	{ "custom78",		WEAPON_CUSTOM78,		NULL }, 	
 	{ "custom79",		WEAPON_CUSTOM79,		NULL }, 	
 	{ "custom80",		WEAPON_CUSTOM80,		NULL }, 	
 	{ "custom81",		WEAPON_CUSTOM81,		NULL }, 	
 	{ "custom82",		WEAPON_CUSTOM82,		NULL }, 	
 	{ "custom83",		WEAPON_CUSTOM83,		NULL }, 	
 	{ "custom84",		WEAPON_CUSTOM84,		NULL }, 	
 	{ "custom85",		WEAPON_CUSTOM85,		NULL }, 	
 	{ "custom86",		WEAPON_CUSTOM86,		NULL }, 	
 	{ "custom87",		WEAPON_CUSTOM87,		NULL }, 	
 	{ "custom88",		WEAPON_CUSTOM88,		NULL }, 	
 	{ "custom89",		WEAPON_CUSTOM89,		NULL }, 	
 	{ "custom90",		WEAPON_CUSTOM90,		NULL }, 	
 	{ "custom91",		WEAPON_CUSTOM91,		NULL }, 	
 	{ "custom92",		WEAPON_CUSTOM92,		NULL }, 	
 	{ "custom93",		WEAPON_CUSTOM93,		NULL }, 	
 	{ "custom94",		WEAPON_CUSTOM94,		NULL }, 	
 	{ "custom95",		WEAPON_CUSTOM95,		NULL }, 	
 	{ "custom96",		WEAPON_CUSTOM96,		NULL }, 	
 	{ "custom97",		WEAPON_CUSTOM97,		NULL }, 	
 	{ "custom98",		WEAPON_CUSTOM98,		NULL }, 	
 	{ "custom99",		WEAPON_CUSTOM99,		NULL }, 	
 	{ "custom100",		WEAPON_CUSTOM100,		NULL }, 		
	{ NULL,			WEAPON_NONE,		NULL }
};

WeaponClassAliasInfo weaponClassAliasInfo[] =
{
	{ "p228",	WEAPONCLASS_PISTOL },
	{ "???",	WEAPONCLASS_PISTOL },
	{ "scout",	WEAPONCLASS_SNIPERRIFLE },
	{ "hegren",	WEAPONCLASS_GRENADE },
	{ "xm1014",	WEAPONCLASS_SHOTGUN },
	{ "c4",		WEAPONCLASS_GRENADE },
	{ "mac10",	WEAPONCLASS_SUBMACHINEGUN },
	{ "aug",	WEAPONCLASS_RIFLE },
	{ "sgren",	WEAPONCLASS_GRENADE },
	{ "elites",	WEAPONCLASS_PISTOL },
	{ "fn57",	WEAPONCLASS_PISTOL },
	{ "ump45",	WEAPONCLASS_SUBMACHINEGUN },
	{ "sg550",	WEAPONCLASS_RIFLE },
	{ "galil",	WEAPONCLASS_RIFLE },
	{ "famas",	WEAPONCLASS_RIFLE },
	{ "usp",	WEAPONCLASS_PISTOL },
	{ "glock",	WEAPONCLASS_PISTOL },
	{ "awp",	WEAPONCLASS_SNIPERRIFLE },
	{ "mp5",	WEAPONCLASS_SUBMACHINEGUN },
	{ "m249",	WEAPONCLASS_MACHINEGUN },
	{ "m3",		WEAPONCLASS_SHOTGUN },
	{ "m1887",		WEAPONCLASS_SHOTGUN },
	{ "m4a1",	WEAPONCLASS_RIFLE },
	{ "tmp",	WEAPONCLASS_SUBMACHINEGUN },
	{ "g3sg1",	WEAPONCLASS_SNIPERRIFLE },
	{ "flash",	WEAPONCLASS_GRENADE },
	{ "deagle",	WEAPONCLASS_PISTOL },
	{ "sg552",	WEAPONCLASS_SNIPERRIFLE },
	{ "ak47",	WEAPONCLASS_RIFLE },
	{ "knife",	WEAPONCLASS_KNIFE },
	{ "p90",	WEAPONCLASS_SUBMACHINEGUN },
	{ "shield",	WEAPONCLASS_PISTOL },
	{ "grenade",	WEAPONCLASS_GRENADE },
	{ "hegrenade",	WEAPONCLASS_GRENADE },
	{ "glock18",	WEAPONCLASS_PISTOL },
	{ "elite",	WEAPONCLASS_PISTOL },
	{ "fiveseven",	WEAPONCLASS_PISTOL },
	{ "mp5navy",	WEAPONCLASS_SUBMACHINEGUN },
	{ "grenade",	WEAPONCLASS_GRENADE },
	{ "pistol",	WEAPONCLASS_PISTOL },
	{ "SMG",	WEAPONCLASS_SUBMACHINEGUN },
	{ "machinegun",	WEAPONCLASS_MACHINEGUN },
	{ "shotgun",	WEAPONCLASS_SHOTGUN },
	{ "rifle",	WEAPONCLASS_RIFLE },
	{ "sniper",	WEAPONCLASS_SNIPERRIFLE }, 		
 	{ "custom1",	WEAPONCLASS_SNIPERRIFLE }, 
 	{ "custom2",	WEAPONCLASS_SNIPERRIFLE }, 	
 	{ "custom3",	WEAPONCLASS_SNIPERRIFLE }, 	
 	{ "custom4",	WEAPONCLASS_SNIPERRIFLE }, 	
 	{ "custom5",	WEAPONCLASS_SNIPERRIFLE }, 	
 	{ "custom6",	WEAPONCLASS_SNIPERRIFLE }, 	
 	{ "custom7",	WEAPONCLASS_SNIPERRIFLE }, 	
 	{ "custom8",	WEAPONCLASS_SNIPERRIFLE }, 	
 	{ "custom9",	WEAPONCLASS_SNIPERRIFLE }, 	
 	{ "custom10",	WEAPONCLASS_SNIPERRIFLE }, 	
 	{ "custom11",	WEAPONCLASS_RIFLE }, 	
 	{ "custom12",	WEAPONCLASS_RIFLE }, 	
 	{ "custom13",	WEAPONCLASS_RIFLE }, 	
 	{ "custom14",	WEAPONCLASS_RIFLE }, 	
 	{ "custom15",	WEAPONCLASS_SNIPERRIFLE }, 	
 	{ "custom16",	WEAPONCLASS_SNIPERRIFLE }, 	
 	{ "custom17",	WEAPONCLASS_SNIPERRIFLE }, 	
 	{ "custom18",	WEAPONCLASS_RIFLE }, 	
 	{ "custom19",	WEAPONCLASS_RIFLE }, 	
 	{ "custom20",	WEAPONCLASS_RIFLE }, 	
 	{ "custom21",	WEAPONCLASS_RIFLE }, 	
 	{ "custom22",	WEAPONCLASS_RIFLE }, 	
 	{ "custom23",	WEAPONCLASS_RIFLE }, 	
 	{ "custom24",	WEAPONCLASS_RIFLE }, 	
 	{ "custom25",	WEAPONCLASS_RIFLE }, 	
 	{ "custom26",	WEAPONCLASS_RIFLE }, 	
 	{ "custom27",	WEAPONCLASS_RIFLE }, 	
 	{ "custom28",	WEAPONCLASS_RIFLE }, 	
 	{ "custom29",	WEAPONCLASS_RIFLE }, 	
 	{ "custom30",	WEAPONCLASS_SHOTGUN }, 	
 	{ "custom31",	WEAPONCLASS_SHOTGUN }, 	
 	{ "custom32",	WEAPONCLASS_SHOTGUN }, 	
 	{ "custom33",	WEAPONCLASS_SHOTGUN }, 	
 	{ "custom34",	WEAPONCLASS_SHOTGUN }, 	
 	{ "custom35",	WEAPONCLASS_SHOTGUN }, 	
 	{ "custom36",	WEAPONCLASS_SHOTGUN }, 	
 	{ "custom37",	WEAPONCLASS_SHOTGUN }, 	
 	{ "custom38",	WEAPONCLASS_SHOTGUN }, 	
 	{ "custom39",	WEAPONCLASS_SHOTGUN }, 	
 	{ "custom40",	WEAPONCLASS_SHOTGUN }, 	
 	{ "custom41",	WEAPONCLASS_RIFLE }, 	
 	{ "custom42",	WEAPONCLASS_RIFLE }, 	
 	{ "custom43",	WEAPONCLASS_RIFLE }, 	
 	{ "custom44",	WEAPONCLASS_RIFLE }, 	
 	{ "custom45",	WEAPONCLASS_RIFLE }, 	
 	{ "custom46",	WEAPONCLASS_RIFLE }, 	
 	{ "custom47",	WEAPONCLASS_RIFLE }, 	
 	{ "custom48",	WEAPONCLASS_RIFLE }, 	
 	{ "custom49",	WEAPONCLASS_RIFLE }, 	
 	{ "custom50",	WEAPONCLASS_RIFLE }, 	
 	{ "custom51",	WEAPONCLASS_RIFLE }, 	
 	{ "custom52",	WEAPONCLASS_RIFLE }, 	
 	{ "custom53",	WEAPONCLASS_RIFLE }, 	
 	{ "custom54",	WEAPONCLASS_RIFLE }, 	
 	{ "custom55",	WEAPONCLASS_RIFLE }, 	
 	{ "custom56",	WEAPONCLASS_RIFLE }, 	
 	{ "custom57",	WEAPONCLASS_RIFLE }, 	
 	{ "custom58",	WEAPONCLASS_RIFLE }, 	
 	{ "custom59",	WEAPONCLASS_RIFLE }, 	
 	{ "custom60",	WEAPONCLASS_RIFLE }, 	
 	{ "custom61",	WEAPONCLASS_RIFLE }, 	
 	{ "custom62",	WEAPONCLASS_RIFLE }, 	
 	{ "custom63",	WEAPONCLASS_RIFLE }, 	
 	{ "custom64",	WEAPONCLASS_RIFLE }, 	
 	{ "custom65",	WEAPONCLASS_RIFLE }, 	
 	{ "custom66",	WEAPONCLASS_RIFLE }, 	
 	{ "custom67",	WEAPONCLASS_RIFLE }, 	
 	{ "custom68",	WEAPONCLASS_RIFLE }, 	
 	{ "custom69",	WEAPONCLASS_RIFLE }, 	
 	{ "custom70",	WEAPONCLASS_RIFLE }, 	
 	{ "custom71",	WEAPONCLASS_RIFLE }, 	
 	{ "custom72",	WEAPONCLASS_RIFLE }, 	
 	{ "custom73",	WEAPONCLASS_RIFLE }, 	
 	{ "custom74",	WEAPONCLASS_RIFLE }, 	
 	{ "custom75",	WEAPONCLASS_RIFLE }, 	
 	{ "custom76",	WEAPONCLASS_RIFLE }, 	
 	{ "custom77",	WEAPONCLASS_RIFLE }, 	
 	{ "custom78",	WEAPONCLASS_RIFLE }, 	
 	{ "custom79",	WEAPONCLASS_RIFLE }, 	
 	{ "custom80",	WEAPONCLASS_RIFLE }, 	
 	{ "custom81",	WEAPONCLASS_RIFLE }, 	
 	{ "custom82",	WEAPONCLASS_RIFLE }, 	
 	{ "custom83",	WEAPONCLASS_RIFLE }, 	
 	{ "custom84",	WEAPONCLASS_RIFLE }, 	
 	{ "custom85",	WEAPONCLASS_RIFLE }, 	
 	{ "custom86",	WEAPONCLASS_RIFLE }, 	
 	{ "custom87",	WEAPONCLASS_RIFLE }, 	
 	{ "custom88",	WEAPONCLASS_RIFLE }, 	
 	{ "custom89",	WEAPONCLASS_RIFLE }, 	
 	{ "custom90",	WEAPONCLASS_RIFLE }, 	
 	{ "custom91",	WEAPONCLASS_RIFLE }, 	
 	{ "custom92",	WEAPONCLASS_RIFLE }, 	
 	{ "custom93",	WEAPONCLASS_RIFLE }, 	
 	{ "custom94",	WEAPONCLASS_RIFLE }, 	
 	{ "custom95",	WEAPONCLASS_RIFLE }, 	
 	{ "custom96",	WEAPONCLASS_RIFLE }, 	
 	{ "custom97",	WEAPONCLASS_RIFLE }, 	
 	{ "custom98",	WEAPONCLASS_RIFLE }, 	
 	{ "custom99",	WEAPONCLASS_RIFLE }, 	
 	{ "custom100",	WEAPONCLASS_RIFLE }, 	
	{ "none",	WEAPONCLASS_NONE },
	{ NULL,		WEAPONCLASS_NONE }
};

WeaponInfoStruct weaponInfo[] =
{
	{ WEAPON_P228,		P228_PRICE,		AMMO_357SIG_PRICE,	AMMO_357SIG_BUY,	P228_MAX_CLIP,		MAX_AMMO_357SIG,	AMMO_357SIG,		"weapon_pyton" },
	{ WEAPON_GLOCK,		GLOCK18_PRICE,		AMMO_9MM_PRICE,		AMMO_9MM_BUY,		GLOCK18_MAX_CLIP,	MAX_AMMO_9MM,		AMMO_9MM,		"weapon_glock18" },
	{ WEAPON_GLOCK18,	GLOCK18_PRICE,		AMMO_9MM_PRICE,		AMMO_9MM_BUY,		GLOCK18_MAX_CLIP,	MAX_AMMO_9MM,		AMMO_9MM,		"weapon_glock18" },
	{ WEAPON_SCOUT,		SCOUT_PRICE,		AMMO_762MM_PRICE,	AMMO_762NATO_BUY,	SCOUT_MAX_CLIP,		MAX_AMMO_762NATO,	AMMO_762NATO,		"weapon_scout" },
	{ WEAPON_XM1014,	XM1014_PRICE,		AMMO_BUCKSHOT_PRICE,	AMMO_BUCKSHOT_BUY,	XM1014_MAX_CLIP,	MAX_AMMO_BUCKSHOT,	AMMO_BUCKSHOT,		"weapon_spas_15" },
	{ WEAPON_MAC10,		MAC10_PRICE,		AMMO_45ACP_PRICE,	AMMO_45ACP_BUY,		MAC10_MAX_CLIP,		MAX_AMMO_45ACP,		AMMO_45ACP,		"weapon_apc" },
	{ WEAPON_AUG,		AUG_PRICE,		AMMO_556MM_PRICE,	AMMO_556NATO_BUY,	AUG_MAX_CLIP,		MAX_AMMO_556NATO,	AMMO_556NATO,		"weapon_aug" },
	{ WEAPON_ELITE,		ELITE_PRICE,		AMMO_9MM_PRICE,		AMMO_9MM_BUY,		ELITE_MAX_CLIP,		MAX_AMMO_9MM,		AMMO_9MM,		"weapon_deagle_dual" },
	{ WEAPON_FIVESEVEN,	FIVESEVEN_PRICE,	AMMO_57MM_PRICE,	AMMO_57MM_BUY,		FIVESEVEN_MAX_CLIP,	MAX_AMMO_57MM,		AMMO_57MM,		"weapon_taurus_raging_bull" },
	{ WEAPON_UMP45,		UMP45_PRICE,		AMMO_45ACP_PRICE,	AMMO_45ACP_BUY, 	UMP45_MAX_CLIP,		MAX_AMMO_45ACP,		AMMO_45ACP,		"weapon_mp5k" },
	{ WEAPON_SG550,		SG550_PRICE,		AMMO_556MM_PRICE,	AMMO_556NATO_BUY,	SG550_MAX_CLIP,		MAX_AMMO_556NATO,	AMMO_556NATO,		"weapon_sg550" },
	{ WEAPON_GALIL,		GALIL_PRICE,		AMMO_556MM_PRICE,	AMMO_556NATO_BUY,	GALIL_MAX_CLIP,		MAX_AMMO_556NATO,	AMMO_556NATO,		"weapon_groza" },
	{ WEAPON_FAMAS,		FAMAS_PRICE,		AMMO_556MM_PRICE,	AMMO_556NATO_BUY,	FAMAS_MAX_CLIP,		MAX_AMMO_556NATO,	AMMO_556NATO,		"weapon_mp7" },
	{ WEAPON_USP,		USP_PRICE,		AMMO_45ACP_PRICE,	AMMO_45ACP_BUY,		USP_MAX_CLIP,		MAX_AMMO_45ACP,		AMMO_45ACP,		"weapon_usp" },
	{ WEAPON_AWP,		AWP_PRICE,		AMMO_338MAG_PRICE,	AMMO_338MAG_BUY,	AWP_MAX_CLIP,		MAX_AMMO_338MAGNUM,	AMMO_338MAGNUM,		"weapon_tactilite_t2" },
	{ WEAPON_MP5N,		MP5NAVY_PRICE,		AMMO_9MM_PRICE,		AMMO_9MM_BUY,		MP5N_MAX_CLIP,		MAX_AMMO_9MM,		AMMO_9MM,		"weapon_p90_mc" },
	{ WEAPON_M249,		M249_PRICE,		AMMO_556MM_PRICE,	AMMO_556NATOBOX_BUY,	M249_MAX_CLIP,		MAX_AMMO_556NATOBOX,	AMMO_556NATOBOX,	"weapon_g36c" },
	{ WEAPON_M3,		M3_PRICE,		AMMO_BUCKSHOT_PRICE,	AMMO_BUCKSHOT_BUY,	M3_MAX_CLIP,		MAX_AMMO_BUCKSHOT,	AMMO_BUCKSHOT,		"weapon_m3" },
	{ WEAPON_M4A1,		M4A1_PRICE,		AMMO_556MM_PRICE,	AMMO_556NATO_BUY,	M4A1_MAX_CLIP,		MAX_AMMO_556NATO,	AMMO_556NATO,		"weapon_sc2010" },
	{ WEAPON_TMP,		TMP_PRICE,		AMMO_9MM_PRICE,		AMMO_9MM_BUY,		TMP_MAX_CLIP,		MAX_AMMO_9MM,		AMMO_9MM,		"weapon_apc" },
	{ WEAPON_G3SG1,		G3SG1_PRICE,		AMMO_762MM_PRICE,	AMMO_762NATO_BUY,	G3SG1_MAX_CLIP,		MAX_AMMO_762NATO,	AMMO_762NATO,		"weapon_cheytac_m200" },
	{ WEAPON_DEAGLE,	DEAGLE_PRICE,		AMMO_50AE_PRICE,	AMMO_50AE_BUY,		DEAGLE_MAX_CLIP,	MAX_AMMO_50AE,		AMMO_50AE,		"weapon_deagle" },
	{ WEAPON_SG552,		SG552_PRICE,		AMMO_556MM_PRICE,	AMMO_556NATO_BUY,	SG552_MAX_CLIP,		MAX_AMMO_556NATO,	AMMO_556NATO,		"weapon_tactilite_t2" },
	{ WEAPON_AK47,		AK47_PRICE,		AMMO_762MM_PRICE,	AMMO_762NATO_BUY,	AK47_MAX_CLIP,		MAX_AMMO_762NATO,	AMMO_762NATO,		"weapon_augblitz" },
	{ WEAPON_P90,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_p90" },
 	{ WEAPON_CUSTOM1,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_l115a1" }, 	
 	{ WEAPON_CUSTOM2,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_ssg69" }, 	
 	{ WEAPON_CUSTOM3,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_kar98k" }, 	
 	{ WEAPON_CUSTOM4,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_l115a1" }, 	
 	{ WEAPON_CUSTOM5,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_cheytac_m200" }, 	
 	{ WEAPON_CUSTOM6,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_ssg69" }, 	
 	{ WEAPON_CUSTOM7,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_cheytac_m200" }, 	
 	{ WEAPON_CUSTOM8,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_l115a1" }, 	
 	{ WEAPON_CUSTOM9,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_cheytac_m200" }, 	
 	{ WEAPON_CUSTOM10,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_cheytac_m200" }, 
	
 	{ WEAPON_CUSTOM11,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_aug_hbar" }, 	
 	{ WEAPON_CUSTOM12,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_aug_a3_silencer" }, 	
 	{ WEAPON_CUSTOM13,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_mp7" }, 	
 	{ WEAPON_CUSTOM14,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_aug" }, 	
 	{ WEAPON_CUSTOM15,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_rangemaster_338" }, 	
 	{ WEAPON_CUSTOM16,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_pgm" }, 	
 	{ WEAPON_CUSTOM17,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_dragunov" }, 	
 	{ WEAPON_CUSTOM18,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_mp7" }, 	
 	{ WEAPON_CUSTOM19,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_aug" }, 	
 	{ WEAPON_CUSTOM20,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_aug_hbar" }, 	
 	{ WEAPON_CUSTOM21,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_mp7" }, 	
 	{ WEAPON_CUSTOM22,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_aug_hbar" }, 	
 	{ WEAPON_CUSTOM23,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_spectre" }, 	
 	{ WEAPON_CUSTOM24,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_aug_hbar" }, 	
 	{ WEAPON_CUSTOM25,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_aug_hbar" }, 	
 	{ WEAPON_CUSTOM26,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_mp7" }, 	
 	{ WEAPON_CUSTOM27,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_mp9" }, 	
 	{ WEAPON_CUSTOM28,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_aksopmod" }, 	
 	{ WEAPON_CUSTOM29,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_mp7" }, 
	
 	{ WEAPON_CUSTOM30,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_m1887" }, 	
 	{ WEAPON_CUSTOM31,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_zombie_s" }, 	
 	{ WEAPON_CUSTOM32,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_spas_15" }, 	
 	{ WEAPON_CUSTOM33,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_m1887" }, 	
 	{ WEAPON_CUSTOM34,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_m1887" }, 	
 	{ WEAPON_CUSTOM35,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_m1887" }, 	
 	{ WEAPON_CUSTOM36,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_m1887" }, 	
 	{ WEAPON_CUSTOM37,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_m1887" }, 	
 	{ WEAPON_CUSTOM38,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_m1887" }, 	
 	{ WEAPON_CUSTOM39,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_m1887" }, 	
 	{ WEAPON_CUSTOM40,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_m1887" }, 
	
 	{ WEAPON_CUSTOM41,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_f2000" }, 	
 	{ WEAPON_CUSTOM42,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_mp7" }, 	
 	{ WEAPON_CUSTOM43,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_aksopmod" }, 	
 	{ WEAPON_CUSTOM44,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_mp7" }, 	
 	{ WEAPON_CUSTOM45,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_aug_hbar" }, 	
 	{ WEAPON_CUSTOM46,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_mp7" }, 	
 	{ WEAPON_CUSTOM47,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_aug_hbar" }, 	
 	{ WEAPON_CUSTOM48,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_aug_hbar" }, 	
 	{ WEAPON_CUSTOM49,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_mp7" }, 	
 	{ WEAPON_CUSTOM50,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_g36c" }, 	
 	{ WEAPON_CUSTOM51,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_aug" }, 	
 	{ WEAPON_CUSTOM52,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_aug" }, 	
 	{ WEAPON_CUSTOM53,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_mp7" }, 	
 	{ WEAPON_CUSTOM54,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_kriss_sv" }, 	
 	{ WEAPON_CUSTOM55,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_mp7" }, 	
 	{ WEAPON_CUSTOM56,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_aksopmod" }, 	
 	{ WEAPON_CUSTOM57,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_aug_hbar" }, 	
 	{ WEAPON_CUSTOM58,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_m4_azure" }, 	
 	{ WEAPON_CUSTOM59,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_aug_hbar" }, 	
 	{ WEAPON_CUSTOM60,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_mp7" }, 	
 	{ WEAPON_CUSTOM61,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_aug_hbar" }, 	
 	{ WEAPON_CUSTOM62,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_p90" }, 	
 	{ WEAPON_CUSTOM63,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_mp7" }, 	
 	{ WEAPON_CUSTOM64,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_mp7" }, 	
 	{ WEAPON_CUSTOM65,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_kriss_sv" }, 	
 	{ WEAPON_CUSTOM66,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_mp7" }, 	
 	{ WEAPON_CUSTOM67,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_aug_hbar" }, 	
 	{ WEAPON_CUSTOM68,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_mp7" }, 	
 	{ WEAPON_CUSTOM69,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_p90" }, 	
 	{ WEAPON_CUSTOM70,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_mp7" }, 	
 	{ WEAPON_CUSTOM71,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_aug_hbar" }, 	
 	{ WEAPON_CUSTOM72,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_aug_hbar" }, 	
 	{ WEAPON_CUSTOM73,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_mp7" }, 	
 	{ WEAPON_CUSTOM74,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_kriss_sv" }, 	
 	{ WEAPON_CUSTOM75,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_kriss_sv" }, 	
 	{ WEAPON_CUSTOM76,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_mp7" }, 	
 	{ WEAPON_CUSTOM77,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_msbs" }, 	
 	{ WEAPON_CUSTOM78,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_mp7" }, 	
 	{ WEAPON_CUSTOM79,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_mp7" }, 	
 	{ WEAPON_CUSTOM80,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_aksopmod" }, 	
 	{ WEAPON_CUSTOM81,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_mp7" }, 	
 	{ WEAPON_CUSTOM82,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_p90" }, 	
 	{ WEAPON_CUSTOM83,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_kriss_sv" }, 	
 	{ WEAPON_CUSTOM84,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_sc2010" }, 	
 	{ WEAPON_CUSTOM85,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_kriss_sv" }, 	
 	{ WEAPON_CUSTOM86,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_aug_hbar" }, 	
 	{ WEAPON_CUSTOM87,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_mp7" }, 	
 	{ WEAPON_CUSTOM88,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_aug_hbar" }, 	
 	{ WEAPON_CUSTOM89,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_mp7" }, 	
 	{ WEAPON_CUSTOM90,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_mp7" }, 	
 	{ WEAPON_CUSTOM91,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_mp7" }, 	
 	{ WEAPON_CUSTOM92,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_mp7" }, 	
 	{ WEAPON_CUSTOM93,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_aksopmod" }, 	
 	{ WEAPON_CUSTOM94,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_mp7" }, 	
 	{ WEAPON_CUSTOM95,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_p90" }, 	
 	{ WEAPON_CUSTOM96,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_p90" }, 	
 	{ WEAPON_CUSTOM97,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_aksopmod" }, 	
 	{ WEAPON_CUSTOM98,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_mp7" }, 	
 	{ WEAPON_CUSTOM99,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_tar21" }, 	
 	{ WEAPON_CUSTOM100,		P90_PRICE,		AMMO_57MM_PRICE,	AMMO_57MM_BUY,		P90_MAX_CLIP,		MAX_AMMO_57MM,		AMMO_57MM,		"weapon_kriss_sv" }, 	
	{ WEAPON_SHIELDGUN,	SHIELDGUN_PRICE,	0,			0,			0,			0,			-1,			NULL },
	{ 0,			0,			0,			0,			0,			0,			-1,			NULL }
};

// Given an alias, return the associated weapon ID
WeaponIdType AliasToWeaponID(const char *alias)
{
	if (alias != NULL)
	{
		for (int i = 0; weaponAliasInfo[i].alias != NULL; ++i)
		{
			if (!Q_stricmp(weaponAliasInfo[i].alias, alias))
				return weaponAliasInfo[i].id;
		}
	}

	return WEAPON_NONE;
}

const char *BuyAliasToWeaponID(const char *alias, WeaponIdType &id)
{
	if (alias)
	{
		for (int i = 0; weaponBuyAliasInfo[i].alias != NULL; ++i)
		{
			if (!Q_stricmp(weaponBuyAliasInfo[i].alias, alias))
			{
				id = weaponBuyAliasInfo[i].id;
				return weaponBuyAliasInfo[i].failName;
			}
		}
	}

	id = WEAPON_NONE;
	return NULL;
}

// Given a weapon ID, return its alias

const char *WeaponIDToAlias(int id)
{
	for (int i = 0; weaponAliasInfo[i].alias != NULL; ++i)
	{
		if (weaponAliasInfo[i].id == id)
			return weaponAliasInfo[i].alias;
	}

	return NULL;
}

WeaponClassType AliasToWeaponClass(const char *alias)
{
	if (alias != NULL)
	{
		for (int i = 0; weaponClassAliasInfo[i].alias != NULL; ++i)
		{
			if (!Q_stricmp(weaponClassAliasInfo[i].alias, alias))
				return weaponClassAliasInfo[i].id;
		}
	}

	return WEAPONCLASS_NONE;
}

WeaponClassType WeaponIDToWeaponClass(int id)
{
	return AliasToWeaponClass(WeaponIDToAlias(id));
}

// Return true if given weapon ID is a primary weapon

bool IsPrimaryWeapon(int id)
{
	switch (id)
	{
	case WEAPON_SCOUT:
	case WEAPON_XM1014:
	case WEAPON_MAC10:
	case WEAPON_AUG:
	case WEAPON_UMP45:
	case WEAPON_SG550:
	case WEAPON_GALIL:
	case WEAPON_FAMAS:
	case WEAPON_AWP:
	case WEAPON_MP5N:
	case WEAPON_M249:
	case WEAPON_M3:
	case WEAPON_M4A1:
	case WEAPON_TMP:
	case WEAPON_G3SG1:
	case WEAPON_SG552:
	case WEAPON_AK47:
	case WEAPON_P90:
	//case WEAPON_SHIELDGUN:

case WEAPON_CUSTOM1: 	
case WEAPON_CUSTOM2: 	
case WEAPON_CUSTOM3: 	
case WEAPON_CUSTOM4: 	
case WEAPON_CUSTOM5: 	
case WEAPON_CUSTOM6: 	
case WEAPON_CUSTOM7: 	
case WEAPON_CUSTOM8: 	
case WEAPON_CUSTOM9: 	
case WEAPON_CUSTOM10: 	
case WEAPON_CUSTOM11: 	
case WEAPON_CUSTOM12: 	
case WEAPON_CUSTOM13: 	
case WEAPON_CUSTOM14: 	
case WEAPON_CUSTOM15: 	
case WEAPON_CUSTOM16: 	
case WEAPON_CUSTOM17: 	
case WEAPON_CUSTOM18: 	
case WEAPON_CUSTOM19: 	
case WEAPON_CUSTOM20: 	
case WEAPON_CUSTOM21: 	
case WEAPON_CUSTOM22: 	
case WEAPON_CUSTOM23: 	
case WEAPON_CUSTOM24: 	
case WEAPON_CUSTOM25: 	
case WEAPON_CUSTOM26: 	
case WEAPON_CUSTOM27: 	
case WEAPON_CUSTOM28: 	
case WEAPON_CUSTOM29: 	
case WEAPON_CUSTOM30: 	
case WEAPON_CUSTOM31: 	
case WEAPON_CUSTOM32: 	
case WEAPON_CUSTOM33: 	
case WEAPON_CUSTOM34: 	
case WEAPON_CUSTOM35: 	
case WEAPON_CUSTOM36: 	
case WEAPON_CUSTOM37: 	
case WEAPON_CUSTOM38: 	
case WEAPON_CUSTOM39: 	
case WEAPON_CUSTOM40: 	
case WEAPON_CUSTOM41: 	
case WEAPON_CUSTOM42: 	
case WEAPON_CUSTOM43: 	
case WEAPON_CUSTOM44: 	
case WEAPON_CUSTOM45: 	
case WEAPON_CUSTOM46: 	
case WEAPON_CUSTOM47: 	
case WEAPON_CUSTOM48: 	
case WEAPON_CUSTOM49: 	
case WEAPON_CUSTOM50: 	
case WEAPON_CUSTOM51: 	
case WEAPON_CUSTOM52: 	
case WEAPON_CUSTOM53: 	
case WEAPON_CUSTOM54: 	
case WEAPON_CUSTOM55: 	
case WEAPON_CUSTOM56: 	
case WEAPON_CUSTOM57: 	
case WEAPON_CUSTOM58: 	
case WEAPON_CUSTOM59: 	
case WEAPON_CUSTOM60: 	
case WEAPON_CUSTOM61: 	
case WEAPON_CUSTOM62: 	
case WEAPON_CUSTOM63: 	
case WEAPON_CUSTOM64: 	
case WEAPON_CUSTOM65: 	
case WEAPON_CUSTOM66: 	
case WEAPON_CUSTOM67: 	
case WEAPON_CUSTOM68: 	
case WEAPON_CUSTOM69: 	
case WEAPON_CUSTOM70: 	
case WEAPON_CUSTOM71: 	
case WEAPON_CUSTOM72: 	
case WEAPON_CUSTOM73: 	
case WEAPON_CUSTOM74: 	
case WEAPON_CUSTOM75: 	
case WEAPON_CUSTOM76: 	
case WEAPON_CUSTOM77: 	
case WEAPON_CUSTOM78: 	
case WEAPON_CUSTOM79: 	
case WEAPON_CUSTOM80: 	
case WEAPON_CUSTOM81: 	
case WEAPON_CUSTOM82: 	
case WEAPON_CUSTOM83: 	
case WEAPON_CUSTOM84: 	
case WEAPON_CUSTOM85: 	
case WEAPON_CUSTOM86: 	
case WEAPON_CUSTOM87: 	
case WEAPON_CUSTOM88: 	
case WEAPON_CUSTOM89: 	
case WEAPON_CUSTOM90: 	
case WEAPON_CUSTOM91: 	
case WEAPON_CUSTOM92: 	
case WEAPON_CUSTOM93: 	
case WEAPON_CUSTOM94: 	
case WEAPON_CUSTOM95: 	
case WEAPON_CUSTOM96: 	
case WEAPON_CUSTOM97: 	
case WEAPON_CUSTOM98: 	
case WEAPON_CUSTOM99: 	
case WEAPON_CUSTOM100: 	
		return true;
	default:
		break;
	}

	return false;
}

// Return true if given weapon ID is a secondary weapon

bool IsSecondaryWeapon(int id)
{
	switch (id)
	{
	case WEAPON_P228:
	case WEAPON_ELITE:
	case WEAPON_FIVESEVEN:
	case WEAPON_USP:
	case WEAPON_GLOCK18:
	case WEAPON_DEAGLE:
		return true;
	default:
		break;
	}

	return false;
}

WeaponInfoStruct *GetWeaponInfo(int weaponID)
{
	for (int i = 0; weaponInfo[i].id != 0; ++i)
	{
		if (weaponInfo[i].id == weaponID)
			return &weaponInfo[i];
	}

	return NULL;
}

bool CanBuyWeaponByMaptype(int playerTeam, WeaponIdType weaponID, bool useAssasinationRestrictions)
{
	if (useAssasinationRestrictions)
	{
		if (playerTeam == CT)
		{
			switch (weaponID)
			{
			case WEAPON_P228:
			case WEAPON_XM1014:
			case WEAPON_AUG:
			case WEAPON_FIVESEVEN:
			case WEAPON_UMP45:
			case WEAPON_SG550:
			case WEAPON_FAMAS:
			case WEAPON_USP:
			case WEAPON_GLOCK18:
			case WEAPON_MP5N:
			case WEAPON_M249:
			case WEAPON_M3:
			case WEAPON_M4A1:
			case WEAPON_TMP:
			case WEAPON_DEAGLE:
			case WEAPON_P90:
			//case WEAPON_SHIELDGUN:
case WEAPON_CUSTOM1: 	
case WEAPON_CUSTOM2: 	
case WEAPON_CUSTOM3: 	
case WEAPON_CUSTOM4: 	
case WEAPON_CUSTOM5: 	
case WEAPON_CUSTOM6: 	
case WEAPON_CUSTOM7: 	
case WEAPON_CUSTOM8: 	
case WEAPON_CUSTOM9: 	
case WEAPON_CUSTOM10: 	
case WEAPON_CUSTOM11: 	
case WEAPON_CUSTOM12: 	
case WEAPON_CUSTOM13: 	
case WEAPON_CUSTOM14: 	
case WEAPON_CUSTOM15: 	
case WEAPON_CUSTOM16: 	
case WEAPON_CUSTOM17: 	
case WEAPON_CUSTOM18: 	
case WEAPON_CUSTOM19: 	
case WEAPON_CUSTOM20: 	
case WEAPON_CUSTOM21: 	
case WEAPON_CUSTOM22: 	
case WEAPON_CUSTOM23: 	
case WEAPON_CUSTOM24: 	
case WEAPON_CUSTOM25: 	
case WEAPON_CUSTOM26: 	
case WEAPON_CUSTOM27: 	
case WEAPON_CUSTOM28: 	
case WEAPON_CUSTOM29: 	
case WEAPON_CUSTOM30: 	
case WEAPON_CUSTOM31: 	
case WEAPON_CUSTOM32: 	
case WEAPON_CUSTOM33: 	
case WEAPON_CUSTOM34: 	
case WEAPON_CUSTOM35: 	
case WEAPON_CUSTOM36: 	
case WEAPON_CUSTOM37: 	
case WEAPON_CUSTOM38: 	
case WEAPON_CUSTOM39: 	
case WEAPON_CUSTOM40: 	
case WEAPON_CUSTOM41: 	
case WEAPON_CUSTOM42: 	
case WEAPON_CUSTOM43: 	
case WEAPON_CUSTOM44: 	
case WEAPON_CUSTOM45: 	
case WEAPON_CUSTOM46: 	
case WEAPON_CUSTOM47: 	
case WEAPON_CUSTOM48: 	
case WEAPON_CUSTOM49: 	
case WEAPON_CUSTOM50: 	
case WEAPON_CUSTOM51: 	
case WEAPON_CUSTOM52: 	
case WEAPON_CUSTOM53: 	
case WEAPON_CUSTOM54: 	
case WEAPON_CUSTOM55: 	
case WEAPON_CUSTOM56: 	
case WEAPON_CUSTOM57: 	
case WEAPON_CUSTOM58: 	
case WEAPON_CUSTOM59: 	
case WEAPON_CUSTOM60: 	
case WEAPON_CUSTOM61: 	
case WEAPON_CUSTOM62: 	
case WEAPON_CUSTOM63: 	
case WEAPON_CUSTOM64: 	
case WEAPON_CUSTOM65: 	
case WEAPON_CUSTOM66: 	
case WEAPON_CUSTOM67: 	
case WEAPON_CUSTOM68: 	
case WEAPON_CUSTOM69: 	
case WEAPON_CUSTOM70: 	
case WEAPON_CUSTOM71: 	
case WEAPON_CUSTOM72: 	
case WEAPON_CUSTOM73: 	
case WEAPON_CUSTOM74: 	
case WEAPON_CUSTOM75: 	
case WEAPON_CUSTOM76: 	
case WEAPON_CUSTOM77: 	
case WEAPON_CUSTOM78: 	
case WEAPON_CUSTOM79: 	
case WEAPON_CUSTOM80: 	
case WEAPON_CUSTOM81: 	
case WEAPON_CUSTOM82: 	
case WEAPON_CUSTOM83: 	
case WEAPON_CUSTOM84: 	
case WEAPON_CUSTOM85: 	
case WEAPON_CUSTOM86: 	
case WEAPON_CUSTOM87: 	
case WEAPON_CUSTOM88: 	
case WEAPON_CUSTOM89: 	
case WEAPON_CUSTOM90: 	
case WEAPON_CUSTOM91: 	
case WEAPON_CUSTOM92: 	
case WEAPON_CUSTOM93: 	
case WEAPON_CUSTOM94: 	
case WEAPON_CUSTOM95: 	
case WEAPON_CUSTOM96: 	
case WEAPON_CUSTOM97: 	
case WEAPON_CUSTOM98: 	
case WEAPON_CUSTOM99: 	
case WEAPON_CUSTOM100: 	
				return true;
			default:
				return false;
			}
		}
		else if (playerTeam == TERRORIST)
		{
			switch (weaponID)
			{
			case WEAPON_P228:
			case WEAPON_MAC10:
			case WEAPON_ELITE:
			case WEAPON_UMP45:
			case WEAPON_GALIL:
			case WEAPON_USP:
			case WEAPON_GLOCK18:
			case WEAPON_AWP:
			case WEAPON_DEAGLE:
			case WEAPON_AK47:
case WEAPON_CUSTOM1: 	
case WEAPON_CUSTOM2: 	
case WEAPON_CUSTOM3: 	
case WEAPON_CUSTOM4: 	
case WEAPON_CUSTOM5: 	
case WEAPON_CUSTOM6: 	
case WEAPON_CUSTOM7: 	
case WEAPON_CUSTOM8: 	
case WEAPON_CUSTOM9: 	
case WEAPON_CUSTOM10: 	
case WEAPON_CUSTOM11: 	
case WEAPON_CUSTOM12: 	
case WEAPON_CUSTOM13: 	
case WEAPON_CUSTOM14: 	
case WEAPON_CUSTOM15: 	
case WEAPON_CUSTOM16: 	
case WEAPON_CUSTOM17: 	
case WEAPON_CUSTOM18: 	
case WEAPON_CUSTOM19: 	
case WEAPON_CUSTOM20: 	
case WEAPON_CUSTOM21: 	
case WEAPON_CUSTOM22: 	
case WEAPON_CUSTOM23: 	
case WEAPON_CUSTOM24: 	
case WEAPON_CUSTOM25: 	
case WEAPON_CUSTOM26: 	
case WEAPON_CUSTOM27: 	
case WEAPON_CUSTOM28: 	
case WEAPON_CUSTOM29: 	
case WEAPON_CUSTOM30: 	
case WEAPON_CUSTOM31: 	
case WEAPON_CUSTOM32: 	
case WEAPON_CUSTOM33: 	
case WEAPON_CUSTOM34: 	
case WEAPON_CUSTOM35: 	
case WEAPON_CUSTOM36: 	
case WEAPON_CUSTOM37: 	
case WEAPON_CUSTOM38: 	
case WEAPON_CUSTOM39: 	
case WEAPON_CUSTOM40: 	
case WEAPON_CUSTOM41: 	
case WEAPON_CUSTOM42: 	
case WEAPON_CUSTOM43: 	
case WEAPON_CUSTOM44: 	
case WEAPON_CUSTOM45: 	
case WEAPON_CUSTOM46: 	
case WEAPON_CUSTOM47: 	
case WEAPON_CUSTOM48: 	
case WEAPON_CUSTOM49: 	
case WEAPON_CUSTOM50: 	
case WEAPON_CUSTOM51: 	
case WEAPON_CUSTOM52: 	
case WEAPON_CUSTOM53: 	
case WEAPON_CUSTOM54: 	
case WEAPON_CUSTOM55: 	
case WEAPON_CUSTOM56: 	
case WEAPON_CUSTOM57: 	
case WEAPON_CUSTOM58: 	
case WEAPON_CUSTOM59: 	
case WEAPON_CUSTOM60: 	
case WEAPON_CUSTOM61: 	
case WEAPON_CUSTOM62: 	
case WEAPON_CUSTOM63: 	
case WEAPON_CUSTOM64: 	
case WEAPON_CUSTOM65: 	
case WEAPON_CUSTOM66: 	
case WEAPON_CUSTOM67: 	
case WEAPON_CUSTOM68: 	
case WEAPON_CUSTOM69: 	
case WEAPON_CUSTOM70: 	
case WEAPON_CUSTOM71: 	
case WEAPON_CUSTOM72: 	
case WEAPON_CUSTOM73: 	
case WEAPON_CUSTOM74: 	
case WEAPON_CUSTOM75: 	
case WEAPON_CUSTOM76: 	
case WEAPON_CUSTOM77: 	
case WEAPON_CUSTOM78: 	
case WEAPON_CUSTOM79: 	
case WEAPON_CUSTOM80: 	
case WEAPON_CUSTOM81: 	
case WEAPON_CUSTOM82: 	
case WEAPON_CUSTOM83: 	
case WEAPON_CUSTOM84: 	
case WEAPON_CUSTOM85: 	
case WEAPON_CUSTOM86: 	
case WEAPON_CUSTOM87: 	
case WEAPON_CUSTOM88: 	
case WEAPON_CUSTOM89: 	
case WEAPON_CUSTOM90: 	
case WEAPON_CUSTOM91: 	
case WEAPON_CUSTOM92: 	
case WEAPON_CUSTOM93: 	
case WEAPON_CUSTOM94: 	
case WEAPON_CUSTOM95: 	
case WEAPON_CUSTOM96: 	
case WEAPON_CUSTOM97: 	
case WEAPON_CUSTOM98: 	
case WEAPON_CUSTOM99: 	
case WEAPON_CUSTOM100: 	
				return true;
			default:
				return false;
			}
		}

		return false;
	}
	if (playerTeam == CT)
	{
		switch (weaponID)
		{
		case WEAPON_P228:
	case WEAPON_GLOCK:
	case WEAPON_SCOUT:
	case WEAPON_HEGRENADE:
	case WEAPON_XM1014:
	case WEAPON_MAC10:
	case WEAPON_AUG:
	case WEAPON_SMOKEGRENADE:
	case WEAPON_ELITE:
	case WEAPON_FIVESEVEN:
	case WEAPON_UMP45:
	case WEAPON_SG550:
	case WEAPON_GALIL:
	case WEAPON_FAMAS:
	case WEAPON_USP:
	case WEAPON_GLOCK18:
	case WEAPON_AWP:
	case WEAPON_MP5N:
	case WEAPON_M249:
	case WEAPON_M3:
	case WEAPON_M4A1:
	case WEAPON_TMP:
	case WEAPON_G3SG1:
	case WEAPON_FLASHBANG:
	case WEAPON_DEAGLE:
	case WEAPON_SG552:
	case WEAPON_AK47:
	case WEAPON_KNIFE:
	case WEAPON_P90:
case WEAPON_CUSTOM1: 	
case WEAPON_CUSTOM2: 	
case WEAPON_CUSTOM3: 	
case WEAPON_CUSTOM4: 	
case WEAPON_CUSTOM5: 	
case WEAPON_CUSTOM6: 	
case WEAPON_CUSTOM7: 	
case WEAPON_CUSTOM8: 	
case WEAPON_CUSTOM9: 	
case WEAPON_CUSTOM10: 	
case WEAPON_CUSTOM11: 	
case WEAPON_CUSTOM12: 	
case WEAPON_CUSTOM13: 	
case WEAPON_CUSTOM14: 	
case WEAPON_CUSTOM15: 	
case WEAPON_CUSTOM16: 	
case WEAPON_CUSTOM17: 	
case WEAPON_CUSTOM18: 	
case WEAPON_CUSTOM19: 	
case WEAPON_CUSTOM20: 	
case WEAPON_CUSTOM21: 	
case WEAPON_CUSTOM22: 	
case WEAPON_CUSTOM23: 	
case WEAPON_CUSTOM24: 	
case WEAPON_CUSTOM25: 	
case WEAPON_CUSTOM26: 	
case WEAPON_CUSTOM27: 	
case WEAPON_CUSTOM28: 	
case WEAPON_CUSTOM29: 	
case WEAPON_CUSTOM30: 	
case WEAPON_CUSTOM31: 	
case WEAPON_CUSTOM32: 	
case WEAPON_CUSTOM33: 	
case WEAPON_CUSTOM34: 	
case WEAPON_CUSTOM35: 	
case WEAPON_CUSTOM36: 	
case WEAPON_CUSTOM37: 	
case WEAPON_CUSTOM38: 	
case WEAPON_CUSTOM39: 	
case WEAPON_CUSTOM40: 	
case WEAPON_CUSTOM41: 	
case WEAPON_CUSTOM42: 	
case WEAPON_CUSTOM43: 	
case WEAPON_CUSTOM44: 	
case WEAPON_CUSTOM45: 	
case WEAPON_CUSTOM46: 	
case WEAPON_CUSTOM47: 	
case WEAPON_CUSTOM48: 	
case WEAPON_CUSTOM49: 	
case WEAPON_CUSTOM50: 	
case WEAPON_CUSTOM51: 	
case WEAPON_CUSTOM52: 	
case WEAPON_CUSTOM53: 	
case WEAPON_CUSTOM54: 	
case WEAPON_CUSTOM55: 	
case WEAPON_CUSTOM56: 	
case WEAPON_CUSTOM57: 	
case WEAPON_CUSTOM58: 	
case WEAPON_CUSTOM59: 	
case WEAPON_CUSTOM60: 	
case WEAPON_CUSTOM61: 	
case WEAPON_CUSTOM62: 	
case WEAPON_CUSTOM63: 	
case WEAPON_CUSTOM64: 	
case WEAPON_CUSTOM65: 	
case WEAPON_CUSTOM66: 	
case WEAPON_CUSTOM67: 	
case WEAPON_CUSTOM68: 	
case WEAPON_CUSTOM69: 	
case WEAPON_CUSTOM70: 	
case WEAPON_CUSTOM71: 	
case WEAPON_CUSTOM72: 	
case WEAPON_CUSTOM73: 	
case WEAPON_CUSTOM74: 	
case WEAPON_CUSTOM75: 	
case WEAPON_CUSTOM76: 	
case WEAPON_CUSTOM77: 	
case WEAPON_CUSTOM78: 	
case WEAPON_CUSTOM79: 	
case WEAPON_CUSTOM80: 	
case WEAPON_CUSTOM81: 	
case WEAPON_CUSTOM82: 	
case WEAPON_CUSTOM83: 	
case WEAPON_CUSTOM84: 	
case WEAPON_CUSTOM85: 	
case WEAPON_CUSTOM86: 	
case WEAPON_CUSTOM87: 	
case WEAPON_CUSTOM88: 	
case WEAPON_CUSTOM89: 	
case WEAPON_CUSTOM90: 	
case WEAPON_CUSTOM91: 	
case WEAPON_CUSTOM92: 	
case WEAPON_CUSTOM93: 	
case WEAPON_CUSTOM94: 	
case WEAPON_CUSTOM95: 	
case WEAPON_CUSTOM96: 	
case WEAPON_CUSTOM97: 	
case WEAPON_CUSTOM98: 	
case WEAPON_CUSTOM99: 	
case WEAPON_CUSTOM100: 	

			return true;
		default:
			return false;
		}
	}
	else if (playerTeam == TERRORIST)
	{
		switch (weaponID)
		{
		case WEAPON_P228:
	case WEAPON_GLOCK:
	case WEAPON_SCOUT:
	case WEAPON_HEGRENADE:
	case WEAPON_XM1014:
	case WEAPON_MAC10:
	case WEAPON_AUG:
	case WEAPON_SMOKEGRENADE:
	case WEAPON_ELITE:
	case WEAPON_FIVESEVEN:
	case WEAPON_UMP45:
	case WEAPON_SG550:
	case WEAPON_GALIL:
	case WEAPON_FAMAS:
	case WEAPON_USP:
	case WEAPON_GLOCK18:
	case WEAPON_AWP:
	case WEAPON_MP5N:
	case WEAPON_M249:
	case WEAPON_M3:
	case WEAPON_M4A1:
	case WEAPON_TMP:
	case WEAPON_G3SG1:
	case WEAPON_FLASHBANG:
	case WEAPON_DEAGLE:
	case WEAPON_SG552:
	case WEAPON_AK47:
	case WEAPON_KNIFE:
	case WEAPON_P90:
case WEAPON_CUSTOM1: 	
case WEAPON_CUSTOM2: 	
case WEAPON_CUSTOM3: 	
case WEAPON_CUSTOM4: 	
case WEAPON_CUSTOM5: 	
case WEAPON_CUSTOM6: 	
case WEAPON_CUSTOM7: 	
case WEAPON_CUSTOM8: 	
case WEAPON_CUSTOM9: 	
case WEAPON_CUSTOM10: 	
case WEAPON_CUSTOM11: 	
case WEAPON_CUSTOM12: 	
case WEAPON_CUSTOM13: 	
case WEAPON_CUSTOM14: 	
case WEAPON_CUSTOM15: 	
case WEAPON_CUSTOM16: 	
case WEAPON_CUSTOM17: 	
case WEAPON_CUSTOM18: 	
case WEAPON_CUSTOM19: 	
case WEAPON_CUSTOM20: 	
case WEAPON_CUSTOM21: 	
case WEAPON_CUSTOM22: 	
case WEAPON_CUSTOM23: 	
case WEAPON_CUSTOM24: 	
case WEAPON_CUSTOM25: 	
case WEAPON_CUSTOM26: 	
case WEAPON_CUSTOM27: 	
case WEAPON_CUSTOM28: 	
case WEAPON_CUSTOM29: 	
case WEAPON_CUSTOM30: 	
case WEAPON_CUSTOM31: 	
case WEAPON_CUSTOM32: 	
case WEAPON_CUSTOM33: 	
case WEAPON_CUSTOM34: 	
case WEAPON_CUSTOM35: 	
case WEAPON_CUSTOM36: 	
case WEAPON_CUSTOM37: 	
case WEAPON_CUSTOM38: 	
case WEAPON_CUSTOM39: 	
case WEAPON_CUSTOM40: 	
case WEAPON_CUSTOM41: 	
case WEAPON_CUSTOM42: 	
case WEAPON_CUSTOM43: 	
case WEAPON_CUSTOM44: 	
case WEAPON_CUSTOM45: 	
case WEAPON_CUSTOM46: 	
case WEAPON_CUSTOM47: 	
case WEAPON_CUSTOM48: 	
case WEAPON_CUSTOM49: 	
case WEAPON_CUSTOM50: 	
case WEAPON_CUSTOM51: 	
case WEAPON_CUSTOM52: 	
case WEAPON_CUSTOM53: 	
case WEAPON_CUSTOM54: 	
case WEAPON_CUSTOM55: 	
case WEAPON_CUSTOM56: 	
case WEAPON_CUSTOM57: 	
case WEAPON_CUSTOM58: 	
case WEAPON_CUSTOM59: 	
case WEAPON_CUSTOM60: 	
case WEAPON_CUSTOM61: 	
case WEAPON_CUSTOM62: 	
case WEAPON_CUSTOM63: 	
case WEAPON_CUSTOM64: 	
case WEAPON_CUSTOM65: 	
case WEAPON_CUSTOM66: 	
case WEAPON_CUSTOM67: 	
case WEAPON_CUSTOM68: 	
case WEAPON_CUSTOM69: 	
case WEAPON_CUSTOM70: 	
case WEAPON_CUSTOM71: 	
case WEAPON_CUSTOM72: 	
case WEAPON_CUSTOM73: 	
case WEAPON_CUSTOM74: 	
case WEAPON_CUSTOM75: 	
case WEAPON_CUSTOM76: 	
case WEAPON_CUSTOM77: 	
case WEAPON_CUSTOM78: 	
case WEAPON_CUSTOM79: 	
case WEAPON_CUSTOM80: 	
case WEAPON_CUSTOM81: 	
case WEAPON_CUSTOM82: 	
case WEAPON_CUSTOM83: 	
case WEAPON_CUSTOM84: 	
case WEAPON_CUSTOM85: 	
case WEAPON_CUSTOM86: 	
case WEAPON_CUSTOM87: 	
case WEAPON_CUSTOM88: 	
case WEAPON_CUSTOM89: 	
case WEAPON_CUSTOM90: 	
case WEAPON_CUSTOM91: 	
case WEAPON_CUSTOM92: 	
case WEAPON_CUSTOM93: 	
case WEAPON_CUSTOM94: 	
case WEAPON_CUSTOM95: 	
case WEAPON_CUSTOM96: 	
case WEAPON_CUSTOM97: 	
case WEAPON_CUSTOM98: 	
case WEAPON_CUSTOM99: 	
case WEAPON_CUSTOM100: 	
			return true;
		default:
			return false;
		}
	}

	return false;
}
